#+title: my config
#+author: justin malu
#+startup: inlineimages content indent

#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src

* language major modes
** emacs lsp booster
#+begin_src emacs-lisp
(defun lsp-booster--advice-json-parse (old-fn &rest args)
  "Try to parse bytecode instead of json."
  (or
   (when (equal (following-char) ?#)
     (let ((bytecode (read (current-buffer))))
       (when (byte-code-function-p bytecode)
         (funcall bytecode))))
   (apply old-fn args)))
(advice-add (if (progn (require 'json)
                       (fboundp 'json-parse-buffer))
                'json-parse-buffer
              'json-read)
            :around
            #'lsp-booster--advice-json-parse)

(defun lsp-booster--advice-final-command (old-fn cmd &optional test?)
  "Prepend emacs-lsp-booster command to lsp CMD."
  (let ((orig-result (funcall old-fn cmd test?)))
    (if (and (not test?)                             ;; for check lsp-server-present?
             (not (file-remote-p default-directory)) ;; see lsp-resolve-final-command, it would add extra shell wrapper
             lsp-use-plists
             (not (functionp 'json-rpc-connection))  ;; native json-rpc
             (executable-find "emacs-lsp-booster"))
        (progn
          (when-let ((command-from-exec-path (executable-find (car orig-result))))  ;; resolve command from exec-path (in case not found in $PATH)
            (setcar orig-result command-from-exec-path))
          (message "Using emacs-lsp-booster for %s!" orig-result)
          (cons "emacs-lsp-booster" orig-result))
      orig-result)))
(advice-add 'lsp-resolve-final-command :around #'lsp-booster--advice-final-command)
#+end_src
** python
*** python-mode
#+begin_src emacs-lisp :tangle yes
(use-package! python
  :ensure nil
  :custom (lsp-pyright-langserver-command "pyright") ;; pyright or basedpyright
  ;; (python-shell-interpreter "python3")
  :hook
  ;; (python-mode . lsp-deferred)
  (python-mode . (lambda () (require 'lsp-pyright) (lsp-deferred)))
  (python-mode . (lambda () (local-set-key (kbd "C-c r") 'python-shell-send-region))))
  ;; (setq-hook! python-mode python-indent-offset 4)
#+end_src
source: [[https://emacs-lsp.github.io/lsp-pyright/]]

*** elpy
#+begin_src emacs-lisp :tangle yes
;; (elpy-enable)
(use-package! elpy
  :defer t
  ;; :init
  ;; (elpy-enable)
  :init (advice-add 'python-mode :before 'elpy-enable))
#+end_src

|---------+--------------------------------------------------------|
| =C-c C-c= | evaluate current script                                |
| =C-RET=   | evaluate current statement (plus nested lines)         |
| =C-c C-z= | switches between your script and the interactive shell |
| =C-c C-d= | display documentation for the thing under cursor       |
|---------+--------------------------------------------------------|
** Lsp Mode
*** lsp ui
#+begin_src emacs-lisp :tangle yes
(use-package! lsp-ui
  :custom
  (lsp-ui-doc-show 'bottom))
#+end_src

https://emacs-lsp.github.io/lsp-ui/

*** lsp treemacs
#+begin_src emacs-lisp :tangle yes
(use-package lsp-treemacs
  :after lsp)
#+end_src

** nix
https://github.com/NixOS/nix-mode

*** nil lsp
nil: An incremental analysis assistant for writing in Nix.
#+begin_src emacs-lisp :tangle no
(use-package! lsp-nix
  ;; :ensure lsp-mode
  :after (lsp-mode)
  :demand t
  :custom
  (lsp-nix-nil-formatter ["nixfmt"]))

(use-package! nix-mode
  :hook (nix-mode . lsp-deferred)
  :ensure nil)
#+end_src

*** nixd
#+begin_src emacs-lisp :tangle no
(use-package! nix-mode
:after lsp-mode
:ensure nil
:hook
(nix-mode . lsp-deferred) ;; So that envrc mode will work
:custom
(lsp-disabled-clients '((nix-mode . nix-nil))) ;; Disable nil so that nixd will be used as lsp-server
:config
(setq lsp-nix-nixd-server-path "nixd"
      lsp-nix-nixd-formatting-command [ "nixfmt" ]
      lsp-nix-nixd-nixpkgs-expr "import <nixpkgs> { }"
      lsp-nix-nixd-nixos-options-expr "(builtins.getFlake \"/home/nb/nixos\").nixosConfigurations.mnd.options"
      lsp-nix-nixd-home-manager-options-expr "(builtins.getFlake \"/home/nb/nixos\").homeConfigurations.\"nb@mnd\".options"))

;; (add-hook!! 'nix-mode-hook
         ;; enable autocompletion with company
         ;; (setq company-idle-delay 0.1))
#+end_src

* DOOM functionality
** fonts

change fonts on the fly [[file:~/org/roam/20250401030930-doom_emacs.org::*To change fonts on the fly:][Link to my notes]]

#+begin_src emacs-lisp
(setq
  doom-symbol-font (font-spec :family "Symbols Nerd Font Mono")
  doom-font (font-spec :family "JetBrains Mono Nerd Font" :size 16 :weight 'medium )
  doom-variable-pitch-font (font-spec :family "VictorMono Nerd Font" :size 14)) ; TODO test this further .
#+end_src

** modeline

works !!...height tooo small thought :height 0.9
#+begin_src emacs-lisp
(custom-set-faces!
  '(mode-line :family "VictorMono Nerd Font" :size 16 )
  '(mode-line-inactive :family "Iosevka Comfy" :size 17))
#+end_src

** custom start mode

#+begin_src emacs-lisp :tangle no
(define-minor-mode start-mode
  "Provide functions for custom start page"
  :lighter " start"
  :keymap (let ((map (make-sparse-keymap)))
                (evil-define-key 'normal start-mode-map
                  (kbd "1") '(lambda () (interactive) (find-file "~/.doom.d/packages.org")))
                map))
;;(add-hook! 'start-mode-hook 'read-only-mode) ;;make start org read only
(provide 'start-mode)
#+end_src

** keybinds
#+begin_src emacs-lisp :tangle no
(keymap-global-set "M-;" 'save-buffer) ;easier saving
;; (keymap-global-set "U" 'evil-redo) ;easier redo :)
#+end_src
** emacs sane
#+begin_src elisp :tangle yes
(use-package! emacs
  :custom

  ;;; Editor
  (tab-width 2)
  (evil-shift-width 2)
  (display-line-numbers-type 'relative)

  ;;; misc
  (bookmark-save-flag 1)
  (uniquify-buffer-name-style 'post-forward) ;nil::
  ;; (electric-pair-mode 1)
  (global-auto-revert-mode t)
  (backup-directory-alist '((".*" . "~/.local/share/Trash/files"))) ; delete to trash instead of create backup files with .el~ suffix (alot of clutter)

  ;;user
  (user-full-name "Justin Malu") ; foor GPG config, email clients, file templates & snippets ; optional
  (user-mail-address "justinmalu@gmail.com")

  ;;scroll
  (scroll-margin 18) ; Adjust the number as needed
  (scroll-conservatively 101) ; TODO test usefulness
  (inhibit-startup-message t)

  :config
  (global-set-key [escape] 'keyboard-escape-quit) ; By default, Emacs requires you to hit ESC three times to escape quit the minibuffer.

  :bind
  (:map evil-normal-state-map
        ("M-;" . save-buffer)
        ("U" . evil-redo)))
#+end_src

#+begin_src elisp :tangle no
(customize-set-variable 'tab-width 2)
#+end_src

+ =Docs=
  Reverting a Buffer:
  The fundamental action is "reverting a buffer," which means replacing the current buffer's text with the text from the file on disk. This is useful when:
    + You've made changes in Emacs but want to discard them and return to the saved version.
    + Another program has modified the file, and you want to update the Emacs buffer to reflect those changes.

  Auto Revert Mode:
  Emacs also provides "auto-revert-mode," which automates this process. When enabled, Emacs periodically checks if the file on disk has changed and automatically updates the buffer. This is particularly useful for:
    + Viewing log files that are constantly being updated.
    + Keeping your Emacs buffer synchronized with files modified by other applications.

** experiment
*** initial buffer
 #+begin_src emacs-lisp :tangle no
(setq initial-buffer-choice "~/.doom.d/config.org") ;
 #+end_src

*** witchmacs stuff

=Witchmacs= :witch:
#+begin_src emacs-lisp :tangle no
(setq-default tab-width 4)
(setq-default standard-indent 4)
(setq c-basic-offset tab-width)
(setq-default electric-indent-inhibit t)
(setq-default indent-tabs-mode t)
(setq backward-delete-char-untabify-method 'nil)
#+end_src

*** hide #+begin_src end_src blocks
**** FIX does not work well...with doom? better way?
see plugin options
#+begin_src emacs-lisp :tangle no
(let ((background-color (face-attribute 'default :background)))
  (set-face-attribute 'org-block-begin-line nil
                      :foreground background-color
                      :background background-color))
#+end_src
*** sane defaults
**** select and type
#+begin_src emacs-lisp :tangle no
(delete-selection-mode 1)
#+end_src
***** TODO see if works/needed
**** weird emacs indent?
Turn off the weird indenting that Emacs does by default.
#+begin_src emacs-lisp :tangle yes
(setq electric-pair-pairs '(
                            (?\{ . ?\})
                            (?\( . ?\))
                            (?\[ . ?\])
                            (?\" . ?\")
                            ))
;; (electric-indent-mode -1)
#+end_src
***** TODO test further
**** creating a new window switches cursor to it
#+begin_src emacs-lisp :tangle yes
 (defun split-and-follow-horizontally ()
	(interactive)
	(split-window-below)
	(balance-windows)
	(other-window 1))
 (global-set-key (kbd "C-x 2") 'split-and-follow-horizontally)

 (defun split-and-follow-vertically ()
	(interactive)
	(split-window-right)
	(balance-windows)
	(other-window 1))
 (global-set-key (kbd "C-x 3") 'split-and-follow-vertically)
#+end_src
**** turn yes-or-no questions into y or no
#+begin_src emacs-lisp :tangle no
(defalias 'yes-or-no-p 'y-or-n-p)
#+end_src
**** defer load most packages for quick startup
#+begin_src emacs-lisp :tangle no
(setq use-package!-always-defer t)
#+end_src
*** delete trailing whitespace
#+begin_src emacs-lisp :tangle no
(add-hook! 'after-save-hook #'delete-trailing-whitespace)
;; or
;; (add-hook! 'after-save-hook #'whitespace-cleanup)
#+end_src
unneeded since we use ws-butler which:
+ only on modified lines
+ replaces trailing whitespace with virtual whitespace
*** default workspace behaviour fix
#+begin_src emacs-lisp :tangle no
(after! persp-mode
  (setq persp-emacsclient-init-frame-behaviour-override
   `(+workspace-current-name))
)
#+end_src
**** TODO see if its fixed/works
* Packages
** dired
#+begin_src emacs-lisp :tangle no
(use-package! dired-open
  :config
  (setq dired-open-extensions '(("gif" . "sxiv")
                                ("jpg" . "sxiv")
                                ("png" . "sxiv")
                                ("mkv" . "mpv")
                                ("mp4" . "mpv"))))

(use-package! peep-dired
  :after dired
  :hook (evil-normalize-keymaps . peep-dired-hook)
  :config
    (evil-define-key 'normal dired-mode-map (kbd "h") 'dired-up-directory)
    (evil-define-key 'normal dired-mode-map (kbd "l") 'dired-open-file) ; use dired-find-file instead if not using dired-open package
    (evil-define-key 'normal peep-dired-mode-map (kbd "j") 'peep-dired-next-file)
    (evil-define-key 'normal peep-dired-mode-map (kbd "k") 'peep-dired-prev-file)
)
#+end_src
** corfu
not sure if after! init works lul

#+begin_src elisp
(use-package! corfu
  :config
  ;; Enable indentation+completion using the TAB key.
  ;; `completion-at-point' is often bound to M-TAB.
  (setq tab-always-indent 'complete) ; try complete if indent is off
  ;; (text-mode-ispell-word-completion nil)
    ;; Hide commands in M-x which do not apply to the current mode.  Corfu
  ;; commands are hidden, since they are not used via M-x. This setting is
  ;; useful beyond Corfu.
  ;; (read-extended-command-predicate #'command-completion-default-include-p)
  )
#+end_src
- If t, hitting TAB always just indents the current line.
- If nil, hitting TAB indents the current line if point is at the left margin
 or in the line's indentation, otherwise it inserts a "real" TAB character.
- If complete, TAB first tries to indent the current line, and if the line
was already indented, then try to complete the thing at point.

Also see tab-first-completion.

Some programming language modes have their own variable to control this,
e.g., c-tab-always-indent, and do not respect this variable.
** Async
#+begin_src emacs-lisp :tangle yes
(use-package! async
  :ensure nil
  :init
  (dired-async-mode 1)) ;Do dired actions asynchronously.
#+end_src

** company
#+begin_src elisp :tangle yes
(use-package! company
  :defer t
  :custom
  (company-idle-delay
        (lambda () (if (company-in-string-or-comment) nil 0.3))) ; delay in seconds
  (company-minimum-prefix-length 3)
  (company-selection-wrap-around t)
  (company-require-match 'never) ; dont need to pick a choice
  (company-tooltip-limit 10))
#+end_src

Company is a text and code completion framework for Emacs. The name stands for "complete anything".

It uses pluggable back-ends and front-ends to retrieve and display completion candidates.

It comes with several back-ends such as Clang, Ispell, CMake, BBDB, Yasnippet, Dabbrev, Etags, Gtags, Files, Keywords and others.
And the CAPF back-end provides a bridge to the standard completion-at-point-functions facility, and thus works with any major mode that uses the common protocol.

To see or change the list of enabled back-ends, type M-x =customize-variable= RET company-backends. Also see its description for information on writing a back-end.

Once installed, enable company-mode with M-x =company-mode=.

usage:
|-----------------------+------------------------------------------------------|
| =C-n / C-p=             | up / down                                            |
| =C-s C-r C-o=           | search through completions                           |
| =M-<digit>=             | quickly complete with one of the first 10 candidates |
| =M-x: company-complete= | to initiate completion manually                      |
|-----------------------+------------------------------------------------------|
source:[[http://company-mode.github.io/manual/Getting-Started.html#Commands-1]]
** centaur tabs
#+begin_src elisp :tangle yes
(use-package! centaur-tabs
  :ensure nil
  :defer t
  :init
  ;; (setq centaur-tabs-mode nil)
  ;; (centaur-tabs-change-fonts "arial" 112)
  ;; (require 'projectile)
  ;; (centaur-tabs-group-by-projectile-project) ; group tabs by projectile
  :config
  (setq centaur-tabs-set-bar nil ; left, over
        centaur-tabs-style 'wave ;alternate, bar, box
        centaur-tabs-icon-type 'all-the-icons ; or nerd-icons
        centaur-tabs-set-icons t
        ;; centaur-tabs-close-button "X"
        ;; centaur-tabs-set-close-button nil
        ;; centaur-tabs-plain-icons t ; for same color as text
        centaur-tabs-gray-out-icons 'buffer
        centaur-tabs-cycle-scope 'tabs
        centaur-tabs-height 18)
  :hook ((nix-mode  . centaur-tabs-mode)
         (python-mode  . centaur-tabs-mode)
         (org-mode . centaur-tabs-local-mode)) ; no centaur tabs on org documents
  :bind
  (:map evil-normal-state-map
        ("g t" . centaur-tabs-forward)
        ("g T" . centaur-tabs-backward)))
#+end_src

centaur-tabs-gray-out-icons 'buffer ; grey icons for unselected buffer
centaur-tabs-height 18 ; 22;;
centaur-tabs-style "bar"
centaur-tabs-modified-marker "•" - Also
  there are two faces to customize the close button string: centaur-tabs-modified-marker-unselected and centaur-tabs-modified-marker-selected

centaur-tabs-set-bar:
- left': displays the bar at the left of the currently selected tab.
- under': displays the bar under the currently selected tab.
- over': displays the bar over the currently selected tab.

=Projectile integration=
You can group your tabs by Projectile’s project. Just use the following function in your configuration:

~(centaur-tabs-group-by-projectile-project)~
This function can be called interactively to enable Projectile grouping. To go back to centaur-tabs’s user defined (or default) buffer grouping function you can interactively call:

~(centaur-tabs-group-buffer-groups)~

** org-auto-tangle

#+begin_src emacs-lisp
(use-package! org-auto-tangle
  :defer t
  ;; :hook (org-mode . org-auto-tangle-mode)
  :hook (org-src-mode . org-auto-tangle-mode)
  :config
  ;; (setq org-auto-tangle-default t) ; set auto_tangle: nil for buffers not to auto tangle
  (setq org-auto-tangle-babel-safelist '("~/system.org" "~/test.org")))
#+end_src

[[github:yilkalargaw/org-auto-tangle]]

** Drag stuff
minor mode for emacs. when drag-stuff-define-keys t
moves text around

#+begin_src emacs-lisp
(use-package! drag-stuff
  :init
  (drag-stuff-global-mode 1)
  (drag-stuff-define-keys))
#+end_src

** highlight TODO
#+begin_src emacs-lisp
(use-package! hl-todo
  :hook (org-mode . hl-todo-mode)
  :config
  (setq hl-todo-highlight-punctuation ":"
        hl-todo-keyword-faces `(("TODO"       warning bold)
                                ("FIXME"      error bold)
                                ("NEVERDO"    warning bold)
                                ("HACK"       font-lock-constant-face bold)
                                ("REVIEW"     font-lock-keyword-face bold)
                                ("NOTE"       success bold)
                                ("DEPRECATED" font-lock-doc-face bold))))
#+end_src
** old | phased out
*** obsidian
#+begin_src emacs-lisp :tangle no
(setq obsidian-directory "~/OBSIDIAN")
#+end_src

#+begin_src emacs-lisp :tangle no
(use-package! obsidian
  :config
  (global-obsidian-mode t)
  (obsidian-backlinks-mode t)
  :custom
  ;; location of obsidian vault
  (obsidian-directory "~/OBSIDIAN")
  ;; Default location for new notes from `obsidian-capture'
  (obsidian-inbox-directory "Inbox")
  ;; Useful if you're going to be using wiki links
  (markdown-enable-wiki-links t)

  ;; These bindings are only suggestions; it's okay to use other bindings
  :bind (:map obsidian-mode-map
              ;; Create note
              ("C-c C-n" . obsidian-capture)
              ;; If you prefer you can use `obsidian-insert-wikilink'
              ("C-c C-l" . obsidian-insert-link)
              ;; Open file pointed to by link at point
              ("C-c C-o" . obsidian-follow-link-at-point)
              ;; Open a different note from vault
              ("C-c C-p" . obsidian-jump)
              ;; Follow a backlink for the current file
              ("C-c C-b" . obsidian-backlink-jump)))
#+end_src

*** junk
**** all the icons
#+begin_src emacs-lisp
(use-package! all-the-icons
  :ensure nil
  :if (display-graphic-p))
#+end_src

#+begin_src emacs-lisp :tangle no
(use-package! all-the-icons-dired
  :hook (dired-mode . (lambda () (all-the-icons-dired-mode t))))
#+end_src
**** FIXME git time machine
#+begin_src emacs-lisp :tangle no
(use-package! git-timemachine
  :after git-timemachine
  :hook (evil-normalize-keymaps . git-timemachine-hook)
  :config
    (evil-define-key 'normal git-timemachine-mode-map (kbd "C-j") 'git-timemachine-show-previous-revision)
    (evil-define-key 'normal git-timemachine-mode-map (kbd "C-k") 'git-timemachine-show-next-revision)
)
#+end_src

**** ultra-scroll
***** TODO make this work? test if needed
#+begin_src emacs-lisp :tangle no
(use-package! ultra-scroll
  ;:load-path "~/code/emacs/ultra-scroll" ; if you git clone'd instead of package-vc-install
  :init
  (setq scroll-conservatively 101 ; important!
        scroll-margin 0)
  :config
  (ultra-scroll-mode 1))
#+end_src

**** Dashboard
***** FIXME does not work
#+begin_src emacs-lisp :tangle no
(use-package! dashboard
  :ensure nil
  :init
  (setq initial-buffer-choice 'dashboard-open)
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-banner-logo-title "Glorious lisp interpreter")
  ;;(setq dashboard-startup-banner 'logo) ;; use standard emacs logo as banner
  (setq dashboard-startup-banner "~/Shibuya/assets/emacs/emacs-dash.png")  ;; use custom image as banner
  (setq dashboard-center-content t) ;; set to 't' for centered content
  (setq dashboard-items '((recents . 5)
                          (agenda . 5 )
                          (bookmarks . 3)
                          (projects . 3)))
  :custom
  (dashboard-modify-heading-icons '((recents . "file-text")
				      (bookmarks . "book")))
  :config
  (dashboard-setup-startup-hook))
#+end_src
* Terminal Modes
** ESHELL
Eshell cannot handle ncurses programs and in certain interpreters (Python, GHCi) selecting previous commands does not work (for now).

I recommend using eshell for light cli work, and using your external terminal emulator of choice for heavier tasks
** term-mode
#+begin_src elisp :tangle no
(use-package! term
  :ensure nil
  :config
  (setq explicit-shell-file-name "bash")
  ;;(setq explicit-zsh-args '())
  (setq term-prompt-regexp "^[^#$%>\n]*[#$%>] *"))
#+end_src
* ORG
** ORG specific settings

[[https://orgmode.org/orgguide.html#Properties]]

#+begin_src emacs-lisp :tangle yes
(use-package! org
  :init
  (setq org-directory "~/org" ; trailing slash important or use expand-file-name(convert file name to absolute and canonicalize/standardize it)
        ;; org-default-notes-file (concat org-directory "/notes.org")
        org-default-notes-file (expand-file-name  "notes.org" org-directory))
  :hook
  (org-mode . (lambda ()
                (vi-tilde-fringe-mode -1)
                (display-line-numbers-mode -1)
                (diff-hl-mode -1)))
  :custom
  (org-fancy-priorities-list '("⚡" "⬆" "⬇" "☕"))
  (org-log-done 'time) ; task done with timestamp
  ;; (org-log-done 'note) ;task done with note prompted to user
  (org-hide-emphasis-markers t)
  (org-tag-alist
      '(;;Places
        ("@home" . ?H)
        ("@school" . ?S)
        ("@babe" . ?B)

        ;;devices
        ("@carthage" . ?C)
        ("@tangier" . ?T)

        ;;activites
        ("@work" . ?W)
        ("@pyrple" . ?P)
        ("@emacs" . ?E)
        ("@nix" . ?N)))
  (org-todo-keywords
      '((sequence "TODO" "WORKING"  "|" "DONE" "CONSIDER"))))
  ;; (org-todo-keywords
  ;;     '((sequence "TODO(t)" "|" "DONE(d)")
  ;;       (sequence "REPORT(r)" "BUG(b)" "KNOWNCAUSE(k)" "|" "FIXED(f)")))

#+end_src

*** experiments
**** zaiste
#+begin_src emacs-lisp :tangle no
(after! org
  (set-face-attribute 'org-link nil
                      :weight 'normal
                      :background nil)
  (set-face-attribute 'org-code nil
                      :foreground "#a9a1e1"
                      :background nil)
  (set-face-attribute 'org-date nil
                      :foreground "#5B6268"
                      :background nil)
  (set-face-attribute 'org-level-1 nil
                      :foreground "steelblue2"
                      :background nil
                      :height 1.2
                      :weight 'normal)
  (set-face-attribute 'org-level-2 nil
                      :foreground "slategray2"
                      :background nil
                      :height 1.0
                      :weight 'normal)
  (set-face-attribute 'org-level-3 nil
                      :foreground "SkyBlue2"
                      :background nil
                      :height 1.0
                      :weight 'normal)
  (set-face-attribute 'org-level-4 nil
                      :foreground "DodgerBlue2"
                      :background nil
                      :height 1.0
                      :weight 'normal)
  (set-face-attribute 'org-level-5 nil
                      :weight 'normal)
  (set-face-attribute 'org-level-6 nil
                      :weight 'normal)
  (set-face-attribute 'org-document-title nil
                      :foreground "SlateGray1"
                      :background nil
                      :height 1.75
                      :weight 'bold)
#+end_src

**** convert md to org
**** FIXME Preserve Indentation On Org-Babel-Tangle
#+begin_src emacs-lisp :tangle no
(setq org-src-preserve-indentation t)
#+end_src
**** bullets mode
#+begin_src emacs-lisp :tangle no
(setq org-bullets-bullet-list '("●" "❀" "◆" "◇" "◖" "☆" "☯" " "))
(add-hook! 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src

#TODO TEST FURTHER
#FIXME not working so far
icons:     large: "◉" "○" "✸" "✿" ;; ♥ ● ◇ ✚ ✜ ☯ ◆ ♠ ♣ ♦ ☢ ❀ ◆ ◖ ▶ |  Small :: ► • ★ ▸

org-bullets-face-name

** org-roam
#+begin_src emacs-lisp
;; (setq org-roam-directory "~/org/org-roam")
(use-package! org-roam
  :init
  (setq org-roam-directory (file-truename "~/org/roam")))
  ;; :custom
  ;; (org-roam-completion-everywhere t) ;default t
  ;; :bind (("C-c n l" . org-roam-buffer-toggle)
  ;;        ("C-c n f" . org-roam-node-find)
  ;;        ("C-c n i" . org-roam-node-insert)
  ;;        ("C-c n c" . org-roam-capture)
         ;; Dailies
         ;; ("C-c n j" . org-roam-dailies-capture-today))
  ;; :config
  ;; (org-roam-db-autosync-enable))
#+end_src
** org-capture
Capture lets you quickly store notes with no workflow interruption
*** my org-capture-template

#+begin_src emacs-lisp
(use-package! org-capture
  :ensure nil
  :bind ("C-c c" . org-capture)
  :config
  ;; (require 'prot-org)
  (setq org-capture-templates
        '(
        ;;; MY STUFF
          ;; ("m" "Movies template" plain
          ;;   (file+headline "bucket-list.org" "Movies to watch");relative to ~/org DIR
          ;;   "- [ ] %?")
          ;; try entry, plain

          ("e" "EMACs" plain
            (file+headline "EmacsTODO.org" "TONEVERDO list - emacs")
            "+ [ ] %?")

          ("b" "Bucket List [ movies books ]") ; group 'em up
          ("bm" "movies" plain
           (file+headline "bucket-list.org" "Movies")
           "+ [ ] %?")
          ("bb" "books" plain
           (file+headline "bucket-list.org" "Books")
           "+ [ ] %?")

          ("d" "Life's Morsels")
          ("dw" "words [w]" plain
           (file+headline "diction.org" "Words") ;TODO see if this can support yassnippets
           "\n %?")
          ("di" "idioms [i]" plain
           (file+headline "diction.org" "Idioms")
           "\n %?")
          ("dp" "phrases [p]" plain
           (file+headline "diction.org" "Phrases")
           "\n %?"))))
#+end_src

**** old template
#+begin_src elisp
;; ("d" "Demo Template" entry
;;   (file+headline "demo.org" "Our first heading");relative to ~/org DIR
;;   "* DEMO TEXT %?")

;; ("o" "Options in prompt" entry
;;  (file+headline "demo.org" "Our second heading")
;;  "* %^{Select your option|ONE|TWO|THREE} %?")

;;; capture region and insert into template ;; attach current time
;; ("t" "Task with a date" entry
;;  (file+headline "demo.org" "Scheduled tasks")
;;  "* %^{Select your option|ONE|TWO|THREE}\n SCHEDULED: %t\n %i %?")

;; ("p" "Prompt for input: " entry
;;     (file+headline "demo.org" "Our first +heading")
;;     "* %^ %?")

;; ("a" "A random template") ; group 'em up
;;     ("at" "submenu - option [t]" entry
;;      (file+headline "demo.org" "Scheduled tasks")
;;      "* %^{Select your option|ONE|TWO|THREE}\n SCHEDULED: %t\n %i %?")
#+end_src
*** howardism

org capture template consists of 3 parts:
+ a key binding
+ a destination, (a file, and some section in that file, like a heading, list item etc)
+ a formatting template

source:[[https://howardism.org/Technical/Emacs/capturing-intro.html][Org capturing intro Howardism]]

*** prot tech :prot:
#+begin_src elisp :tangle no
(use-package! org-capture
  :ensure nil
  :bind ("C-c c" . org-capture)
  :config
  ;; (require 'prot-org)

  (setq org-capture-templates
        `(("u" "Unprocessed" entry
           (file+headline "tasks.org" "Unprocessed")
           ,(concat "* %^{Title}\n"
                    ":PROPERTIES:\n"
                    ":CAPTURED: %U\n"
                    ":CUSTOM_ID: h:%(format-time-string \"%Y%m%dT%H%M%S\")\n"
                    ":END:\n\n"
                    "%a\n%i%?")
           :empty-lines-after 1)
          ("w" "Wishlist" entry
           (file+olp "tasks.org" "All tasks" "Wishlist")
           ,(concat "* %^{Title} %^g\n"
                    ":PROPERTIES:\n"
                    ":CAPTURED: %U\n"
                    ":CUSTOM_ID: h:%(format-time-string \"%Y%m%dT%H%M%S\")\n"
                    ":END:\n\n"
                    "%a\n%?")
           :empty-lines-after 1)
          ("t" "Task to do" entry
           (file+headline "tasks.org" "All tasks")
           ,(concat "* TODO %^{Title} %^g\n"
                    ":PROPERTIES:\n"
                    ":CAPTURED: %U\n"
                    ":CUSTOM_ID: h:%(format-time-string \"%Y%m%dT%H%M%S\")\n"
                    ":END:\n\n"
                    "%a\n%?")
           :empty-lines-after 1)
          ("s" "Select file and heading to add to" entry
           (function prot-org-select-heading-in-file)
           ,(concat "* TODO %^{Title}%?\n"
                    ":PROPERTIES:\n"
                    ":CAPTURED: %U\n"
                    ":CUSTOM_ID: h:%(format-time-string \"%Y%m%dT%H%M%S\")\n"
                    ":END:\n\n")
           :empty-lines-after 1)

          ;; NOTE 2024-11-24: I am not using this, but am keeping it
          ;; here because the approach is good.

          ;; ("c" "Clock in and do immediately" entry
          ;;  (file+headline "tasks.org" "Clocked tasks")
          ;;  ,(concat "* TODO %^{Title}\n"
          ;;           ":PROPERTIES:\n"
          ;;           ":EFFORT: %^{Effort estimate in minutes|5|10|15|30|45|60|90|120}\n"
          ;;           ":END:\n\n"
          ;;           "%a\n")
          ;;  :prepend t
          ;;  :clock-in t
          ;;  :clock-keep t
          ;;  :immediate-finish t
          ;;  :empty-lines-after 1)
          ("p" "Private lesson or service" entry
           (file "coach.org")
           #'prot-org-capture-coach
           :prepend t
           :empty-lines 1)
          ("P" "Private service clocked" entry
           (file+headline "coach.org" "Clocked services")
           #'prot-org-capture-coach-clock
           :prepend t
           :clock-in t
           :clock-keep t
           :immediate-finish t
           :empty-lines 1)))

  ;; NOTE 2024-11-10: I realised that I was not using this enough, so
  ;; I decided to simplify my setup.  Keeping it here, in case I need
  ;; it again.

  ;; (setq org-capture-templates-contexts
  ;;       '(("e" ((in-mode . "notmuch-search-mode")
  ;;               (in-mode . "notmuch-show-mode")
  ;;               (in-mode . "notmuch-tree-mode")))))
  )
#+end_src
*** escape codes
|------------------+-----------------------------------------------------------|
| special =%= escape | does                                                      |
|------------------+-----------------------------------------------------------|
| =%a=               | annotation, normally the link created with org-store-link |
| =%i=               | with active region selected, insert it at point           |
| =%t=  =%T=           | timestamp, date only, or date and time                    |
| =%^t=              | prompt for timestamp                                      |
| =%u=  =%U=           | like above, but inactive timestamps                       |
| =%?=               | after completing the template, position point here        |
| =%^=               | input/prompt                                              |
|------------------+-----------------------------------------------------------|
**** time management
dont have to select manually you can:
+ relative time +3d

*** shortcurts
|----------------------+-----------------+----------------------------------------------------------------------------|
| command              | keymap          | does                                                                       |
|----------------------+-----------------+----------------------------------------------------------------------------|
| org-capture          | =M-x org-capture= | start capture process, placing you into a narrowed indirect buffer to edit |
| org-capture-finalize | =C-c C-c=         |                                                                            |
| org-capture-refile   | =C-c C-w=         | Finalize the capture process by refiling the note to a different place     |
| org-capture-kill     | =C-c C-k=         | Abort the capture process and return to the previous state.                |
|----------------------+-----------------+----------------------------------------------------------------------------|
*** templates
**** thoughtbot guy
#+begin_src emacs-lisp :tangle no
(setq org-capture-templates
      `(("t"    ;hotkey
         "Todo list item"  ; name
         entry ;type
         ;heading type and title
         (file+headline org-default-notes-file "Tasks")
         "* TODO %?\n %i\n %a" ;template
         )))
#+end_src

**** source?? - nice stuff
# default location for capture mode?
#+begin_src emacs-lisp :tangle no
(setq org-agenda-files (list "inbox.org"))
#+end_src
then we can setup a specific capture template for inbox:

#+begin_src emacs-lisp :tangle no
(setq org-capture-templates
       `(("i" "Inbox" entry  (file "inbox.org")
        ,(concat "* TODO %?\n"
                 "/Entered on/ %U"))))
#+end_src
**** capture templates :prot:
more: manual

You can use templates for different types of capture items, and for different target locations. Say you would like to use one template to create general TODO entries, and you want to put these entries under the heading ‘Tasks’ in your file ‘~/org/gtd.org’. Also, a date tree in the file ‘journal.org’ should capture journal entries. A possible configuration would look like:

If you then press =t= from the capture menu, Org will prepare the template for you like this:

#+begin_src emacs-lisp :tangle no
(setq org-capture-templates
      '(("t" "Todo" entry (file+headline "~/org/gtd.org" "Tasks")
         "* TODO %?\n  %i\n  %a")
        ("j" "Journal" entry (file+datetree "~/org/journal.org")
         "* %?\nEntered on %U\n  %i\n  %a")))
#+end_src



[[https://www.labri.fr/perso/nrougier/GTD/index.html][very nice tutorials]]
** org-agenda

(key desc type match settings files)

Doom Emacs sets (org-agenda-start-day "-3d").

*** pro tech :prot:
#+begin_src emacs-lisp :tangle yes
(load! "maluware-org-agenda") ; imports maluware-orgAgenda.el

(setq org-agenda-custom-commands
      `(
        ("D" "Today's view"
         ((todo "WAIT"
                ((org-agenda-overriding-header "Tasks on hold\n")))
         (agenda ""
                 ((org-agenda-block-separator nil) ;"*"
                  (org-agenda-span 1) ;7:: how many days should it span
                  (org-deadline-warning-days 0) ; remove warnings for events not for today
                  ;; (org-agenda-day-face-function (lambda (date) 'org-agenda-date)) ; remove underline on todays date
                  ;; (org-agenda-format-date "%A %-e %B %Y") ;modify date
                  ;; (org-agenda-fontify-priorities nil)
                  (org-agenda-start-day nil)
                  (org-agenda-overriding-header "\nDaily agenda view\n")))
         ))
        ("P" "Protesilaos"
         ,maluware-custom-org-daily-agenda)
        ))
#+end_src
*** external variable files
For neater/shorter presentation
**** defvar maluware-org-custom-daily-agenda
#+begin_src emacs-lisp :tangle maluware-org-agenda.el
(defvar maluware-custom-org-daily-agenda
  `((tags-todo "*"
     ((org-agenda-skip-function '(org-agenda-skip-if nil '(timestamp)))
      (org-agenda-skip-function
       `(org-agenda-skip-entry-if
         'notregexp ,(format "\\[#%s\\]" (char-to-string org-priority-highest))))
      (org-agenda-block-separator nil)
      (org-agenda-overriding-header "Important tasks without a date\n")))
    (agenda "" ((org-agenda-span 1)
                (org-deadline-warning-days 0)
                (org-agenda-block-separator nil)
                (org-scheduled-past-days 0)
                ;; We don't need the `org-agenda-date-today'
                ;; highlight because that only has a practical
                ;; utility in multi-day views.
                (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
                (org-agenda-format-date "%A %-e %B %Y")
                (org-agenda-overriding-header "\nToday's agenda\n")))
    (agenda "" ((org-agenda-start-on-weekday nil)
                (org-agenda-start-day "+1d")
                (org-agenda-span 3)
                (org-deadline-warning-days 0)
                (org-agenda-block-separator nil)
                (org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                (org-agenda-overriding-header "\nNext three days\n")))
    (agenda "" ((org-agenda-time-grid nil)
                (org-agenda-start-on-weekday nil)
                ;; We don't want to replicate the previous section's
                ;; three days, so we start counting from the day after.
                (org-agenda-start-day "+4d")
                (org-agenda-span 14)
                (org-agenda-show-all-dates nil)
                (org-deadline-warning-days 0)
                (org-agenda-block-separator nil)
                (org-agenda-entry-types '(:deadline))
                (org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                (org-agenda-overriding-header "\nUpcoming deadlines (+14d)\n"))))
  "Custom agenda for use in `org-agenda-custom-commands'.")
#+end_src

***** org-agenda-custom-commands
#+begin_src emacs-lisp :tangle no
(setq org-agenda-custom-commands
      `(("A" "Daily agenda and top priority tasks"
         ((tags-todo "*"
                     ((org-agenda-skip-function '(org-agenda-skip-if nil '(timestamp)))
                      (org-agenda-skip-function
                       `(org-agenda-skip-entry-if
                         'notregexp ,(format "\\[#%s\\]" (char-to-string org-priority-highest))))
                      (org-agenda-block-separator nil)
                      (org-agenda-overriding-header "Important tasks without a date\n")))
          (agenda "" ((org-agenda-span 1)
                      (org-deadline-warning-days 0)
                      (org-agenda-block-separator nil)
                      (org-scheduled-past-days 0)
                      ;; We don't need the `org-agenda-date-today'
                      ;; highlight because that only has a practical
                      ;; utility in multi-day views.
                      (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
                      (org-agenda-format-date "%A %-e %B %Y")
                      (org-agenda-overriding-header "\nToday's agenda\n")))
          (agenda "" ((org-agenda-start-on-weekday nil)
                      (org-agenda-start-day "+1d")
                      (org-agenda-span 3)
                      (org-deadline-warning-days 0)
                      (org-agenda-block-separator nil)
                      (org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                      (org-agenda-overriding-header "\nNext three days\n")))
          (agenda "" ((org-agenda-time-grid nil)
                      (org-agenda-start-on-weekday nil)
                      ;; We don't want to replicate the previous section's
                      ;; three days, so we start counting from the day after.
                      (org-agenda-start-day "+4d")
                      (org-agenda-span 14)
                      (org-agenda-show-all-dates nil)
                      (org-deadline-warning-days 0)
                      (org-agenda-block-separator nil)
                      (org-agenda-entry-types '(:deadline))
                      (org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                      (org-agenda-overriding-header "\nUpcoming deadlines (+14d)\n")))))
        ("P" "Plain text daily agenda and top priorities"
         ((tags-todo "*"
                     ((org-agenda-skip-function '(org-agenda-skip-if nil '(timestamp)))
                      (org-agenda-skip-function
                       `(org-agenda-skip-entry-if
                         'notregexp ,(format "\\[#%s\\]" (char-to-string org-priority-highest))))
                      (org-agenda-block-separator nil)
                      (org-agenda-overriding-header "Important tasks without a date\n")))
          (agenda "" ((org-agenda-span 1)
                      (org-deadline-warning-days 0)
                      (org-agenda-block-separator nil)
                      (org-scheduled-past-days 0)
                      ;; We don't need the `org-agenda-date-today'
                      ;; highlight because that only has a practical
                      ;; utility in multi-day views.
                      (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
                      (org-agenda-format-date "%A %-e %B %Y")
                      (org-agenda-overriding-header "\nToday's agenda\n")))
          (agenda "" ((org-agenda-start-on-weekday nil)
                      (org-agenda-start-day "+1d")
                      (org-agenda-span 3)
                      (org-deadline-warning-days 0)
                      (org-agenda-block-separator nil)
                      (org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                      (org-agenda-overriding-header "\nNext three days\n")))
          (agenda "" ((org-agenda-time-grid nil)
                      (org-agenda-start-on-weekday nil)
                      ;; We don't want to replicate the previous section's
                      ;; three days, so we start counting from the day after.
                      (org-agenda-start-day "+4d")
                      (org-agenda-span 14)
                      (org-agenda-show-all-dates nil)
                      (org-deadline-warning-days 0)
                      (org-agenda-block-separator nil)
                      (org-agenda-entry-types '(:deadline))
                      (org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                      (org-agenda-overriding-header "\nUpcoming deadlines (+14d)\n"))))
         ((org-agenda-with-colors nil)
          (org-agenda-prefix-format "%t %s")
          (org-agenda-current-time-string ,(car (last org-agenda-time-grid)))
          (org-agenda-fontify-priorities nil)
          (org-agenda-remove-tags t))
         ("agenda.txt"))))
#+end_src

***** org-agenda-custom-commands
#+begin_src emacs-lisp :tangle no
(setq org-agenda-custom-commands
      `(("A" "Daily agenda and top priority tasks"
         ,prot-org-custom-daily-agenda)
        ("P" "Plain text daily agenda and top priorities"
         ,prot-org-custom-daily-agenda
         ((org-agenda-with-colors nil)
          (org-agenda-prefix-format "%t %s")
          (org-agenda-current-time-string ,(car (last org-agenda-time-grid)))
          (org-agenda-fontify-priorities nil)
          (org-agenda-remove-tags t))
         ("agenda.txt"))))
#+end_src
**** experiment custom-org-daily-agenda
#+begin_src emacs-lisp :tangle no
(defvar maluware-custom-org-daily-agenda
         `((tags-todo "*"
            (org-agenda-skip-function '(org-agenda-skip-if nil '(timestamp))))
           (org-agenda-skip-function
            `(org-agenda-skip-entry-if
              'notrege))
           (todo "WAIT"
                ((org-agenda-overriding-header "Tasks on hold\n")))
         (agenda ""
                 ((org-agenda-block-separator nil) ;"*"
                  ;; (org-agenda-span 1) ;7:: how many days should it span
                  ;; (org-deadline-warning-days 0) ;events not for today
                  (org-agenda-day-face-function (lambda (date) 'org-agenda-date)) ; remove underline on todays date
                  ;; (org-agenda-format-date "%A %-e %B %Y") ;modify date
                  ;; (org-agenda-fontify-priorities nil)
                  ;; org-agenda-skip-function
                  (org-agenda-overriding-header "\nDaily agenda\n"))))
  )
#+end_src
*** from manual
#+begin_src emacs-lisp :tangle no
(setq org-agenda-custom-commands
    '(("h" "Agenda and Home-related tasks"
        ((agenda "")
        (tags-todo "home")
        (tags "garden")))
      ("o" "Agenda and Office-related tasks"
        ((agenda "")
        (tags-todo "work")
        (tags "office")))
      ))
#+end_src
*** worg tricks
**** Colorize clocking tasks with a block
[[https://orgmode.org/worg/org-hacks.html][org hacks -worg]]
#+begin_src emacs-lisp :tangle no
;; work with org-agenda dispatcher [c] "Today Clocked Tasks" to view today's clocked tasks.
(defun org-agenda-log-mode-colorize-block ()
  "Set different line spacing based on clock time duration."
  (save-excursion
    (let* ((colors (cl-case (alist-get 'background-mode (frame-parameters))
                                 ('light
                                  (list "#F6B1C3" "#FFFF9D" "#BEEB9F" "#ADD5F7"))
                                 ('dark
                                  (list "#aa557f" "DarkGreen" "DarkSlateGray" "DarkSlateBlue"))))
           pos
           duration)
      (nconc colors colors)
      (goto-char (point-min))
      (while (setq pos (next-single-property-change (point) 'duration))
        (goto-char pos)
        (when (and (not (equal pos (point-at-eol)))
                   (setq duration (org-get-at-bol 'duration)))
          ;; larger duration bar height
          (let ((line-height (if (< duration 15) 1.0 (+ 0.5 (/ duration 30))))
                (ov (make-overlay (point-at-bol) (1+ (point-at-eol)))))
            (overlay-put ov 'face `(:background ,(car colors) :foreground "black"))
            (setq colors (cdr colors))
            (overlay-put ov 'line-height line-height)
            (overlay-put ov 'line-spacing (1- line-height))))))))

(add-hook! 'org-agenda-finalize-hook #'org-agenda-log-mode-colorize-block)
#+end_src

**** Go back to the previous top-level heading
***** TODO test further
#+begin_src emacs-lisp :tangle no
(defun org-back-to-top-level-heading ()
  "Go back to the current top level heading."
  (interactive)
  (or (re-search-backward "^\* " nil t)
      (goto-char (point-min))))
#+end_src
* sources:
https://github.com/snackon/Witchmacs/
* DOCS
** docs | old
*** fonts
source: [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Fonts.html][emacs - fonts GNU manual]]
‘slant’
One of ‘italic’, ‘oblique’, or ‘roman’.

‘weight’
One of ‘light’, ‘medium’, ‘demibold’, ‘bold’ or ‘black’.

‘style’
Some fonts define special styles which are a combination of slant and weight. For instance, ‘Dejavu Sans’ defines the ‘book’ style, which overrides the slant and weight properties.

‘width’
One of ‘condensed’, ‘normal’, or ‘expanded’.

‘spacing’
One of ‘monospace’, ‘proportional’, ‘dual-width’, or ‘charcell’.

 Doom exposes five (optional) variables for controlling fonts in Doom:

 - `doom-font' -- the primary font to use
 - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
   - used in websites? eww?
   - headers?

*** theme
**** load theme

 There are =two ways= to load a theme. Both assume the theme is installed and
 available.

 You can either set =doom-theme= or =manually= load a theme with the =load-theme= function (This is the =default=:)

**** favs
***** dark
- solarized-dark
- one
- horizon - nice red accents and purple
- dracula
- solarized-dark-high-contrast
- ayu-mirage
- snazzy
- moonlight
- material - nice purple dotts and cursor
- monokai-octagon

***** light
- doom-solarized-light
- earl grey
***** really light white light
- doom-winter-is-coming-light
- ayu light
- one light
***** pastel
- ephemeral
- nord-aurora
*** nerd font experiement
**** mononoki
kinda nice and kawaii
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "Mononoki Nerd Font" :size 17 :weight 'semi-bold ))
#+end_src
**** iosevka
***** comfy
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "Iosevka Comfy" :size 16 :weight 'regular ))
#+end_src
***** term
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "Iosevka Nerd Font" :size 16 :weight 'medium ))
#+end_src

**** zed mono
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "ZedMono Nerd Font" :size 17 :weight 'regular ))
#+end_src

**** martian mono
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "MartianMono Nerd Font" :size 14 :weight 'regular ))
#+end_src

**** caskaydia
***** code
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "Cascadia Code" :size 15 :weight 'semibold ))
#+end_src
***** mono
kinda nice
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "Cascadia Mono" :size 15 :weight 'semibold ))
#+end_src

**** lilex
nice l and i
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "Lilex Nerd Font" :size 15 :weight 'normal ))
#+end_src

**** fira
nice defaults
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "FiraMono Nerd Font" :size 15 :weight 'medium ))
#+end_src

**** shure
boxy nice stuff 😃
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "ShureTechMono Nerd Font" :size 15 :weight 'medium ))
#+end_src

**** lekton
nice little font actually :)
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "Lekton Nerd Font Mono" :size 18 :weight 'bold ))
#+end_src

**** space mono
use with rofi as well...clean cut font but kinda thin and no semibold
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "SpaceMono Nerd Font Mono" :size 16 :weight 'regular ))
#+end_src

**** Monofur
kawaii - but does not look nice for ide maybe for ui?
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "Monofur Nerd Font" :size 18  :weight 'regular ))
#+end_src

**** SauceCode Pro
#+begin_src emacs-lisp :tangle no
(setq
 doom-font (font-spec :family "SauceCodePro Nerd Font" :size 16  :weight 'regular ))
#+end_src

**** Geist
sublime... kinda similar to monaspace... weird ls , i is clean 0 o O
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "GeistMono Nerd Font" :size 16  :weight 'normal ))
#+end_src

**** monaspace
one family, 5 fonts, 3 variable axes


|------+---------+--------------------|
| abbr | name    | font (actual)      |
|------+---------+--------------------|
| Ne   | Neon    | Neo-grotesque sans |
| Ar   | Argon   | Humanist sans      |
| Xe   | Xenon   | Slab serif         |
| Ra   | Radon   | Handwriting        |
| Kr   | Kyrpton | Mechanical sans    |
|------+---------+--------------------|

#+begin_src emacs-lisp :tangle no
;; (setq doom-font (font-spec :family "Monaspace Neon" :size 16 :weight 'semibold ))
(setq doom-font (font-spec :family "Monaspace Krypton" :size 16 :weight 'normal ))
#+end_src

*** options
- var:doom-font: the primary font for Emacs to use.
- var:doom-variable-pitch-font: used for non-monospace fonts (e.g. when using variable-pitch-mode or mixed-pitch-mode). Popular for text modes, like Org or Markdown.
- var:doom-emoji-font: used for rendering emoji. Only needed if you want to use a font other than your operating system’s default.
- var:doom-symbol-font: used for rendering symbols.
- var:doom-serif-font: the sans-serif font to use wherever the face:fixed-pitch-serif face is used.
- var:doom-big-font: the large font to use when fn:doom-big-font-mode is active.
