#+title: my config
#+author: justin malu
#+startup: inlineimages content indent
#+auto_tangle: t

#+begin_src emacs-lisp :tangle yes
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src

* language major modes
NOTE: if treesitter available the mode has an appended -ts-mode eg python-ts-mode

** emacs lsp booster
#+begin_src emacs-lisp :tangle yes
(defun lsp-booster--advice-json-parse (old-fn &rest args)
  "Try to parse bytecode instead of json."
  (or
   (when (equal (following-char) ?#)
     (let ((bytecode (read (current-buffer))))
       (when (byte-code-function-p bytecode)
         (funcall bytecode))))
   (apply old-fn args)))
(advice-add (if (progn (require 'json)
                       (fboundp 'json-parse-buffer))
                'json-parse-buffer
              'json-read)
            :around
            #'lsp-booster--advice-json-parse)

(defun lsp-booster--advice-final-command (old-fn cmd &optional test?)
  "Prepend emacs-lsp-booster command to lsp CMD."
  (let ((orig-result (funcall old-fn cmd test?)))
    (if (and (not test?)                             ;; for check lsp-server-present?
             (not (file-remote-p default-directory)) ;; see lsp-resolve-final-command, it would add extra shell wrapper
             lsp-use-plists
             (not (functionp 'json-rpc-connection))  ;; native json-rpc
             (executable-find "emacs-lsp-booster"))
        (progn
          (when-let ((command-from-exec-path (executable-find (car orig-result))))  ;; resolve command from exec-path (in case not found in $PATH)
            (setcar orig-result command-from-exec-path))
          (message "Using emacs-lsp-booster for %s!" orig-result)
          (cons "emacs-lsp-booster" orig-result))
      orig-result)))
(advice-add 'lsp-resolve-final-command :around #'lsp-booster--advice-final-command)
#+end_src
** python mode
https://renzmann.github.io/posts/006_emacs_2_python/
*** elpy
#+begin_src emacs-lisp :tangle yes
(use-package! elpy
  :defer t
  :init
  (advice-add 'python-ts-mode :before 'elpy-enable)
  :config
  ;; (elpy-folding-fringe-indicators t)
  ;; (elpy-modules (delq 'elpy-module-flymake elpy-modules))
  ;; (setq elpy-modules (delq 'elpy-module-highlight-indentation elpy-modules)) ; disable elpy indentation guide
  ;; (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
  (setq elpy-modules (cl-set-difference
                      elpy-modules
                      '(elpy-module-highlight-indentation
                        elpy-module-flymake)))
  :hook
  (elpy-mode . flycheck-mode))
#+end_src

*** ipython
#+begin_src elisp :tangle yes
(use-package! python
  :custom
  (python-shell-interpreter "ipython")
  ;; (python-shell-interpreter-args "-i --simple-prompt" ) ; --no-color-info
  ;; (python-shell-prompt-detect-failure-warning nil)
  ;; :config
  ;; (setq +python-ipython-repl-args '("-i" "--simple-prompt" "--no-color-info"))
  ;; (setq +python-jupyter-repl-args '("--simple-prompt"))
  :hook
  (python-ts-mode . (lambda ()
                   (setq-local lsp-pyright-langserver-command "basedpyright") ;; pyright or basedpyright
                   (setq +format-with 'black)
                   (lsp-deferred)
                   (local-set-key (kbd "C-c r") 'python-shell-send-region))))

(setq lsp-pyright-langserver-command "basedpyright")
#+end_src

*** jupyter
#+begin_src emacs-lisp :tangle no
(use-package! python
  :config
  (setq python-shell-interpreter "jupyter"
        python-shell-interpreter-args "console --simple-prompt"
        python-shell-prompt-detect-failure-warning nil)
  (add-to-list 'python-shell-completion-native-disabled-interpreters "jupyter")
  :hook
  (python-ts-mode . (lambda ()
                   (setq-local lsp-pyright-langserver-command "basedpyright") ;; pyright or basedpyright
                   (setq +format-with 'black)
                   (lsp-deferred)
                   (local-set-key (kbd "C-c r") 'python-shell-send-region))))
#+end_src

source: [[https://emacs-lsp.github.io/lsp-pyright/]]

** Lsp Mode
*** lsp ui
UI integrations for lsp-mode

https://github.com/emacs-lsp/lsp-ui

By default, =lsp-mode= automatically activates =lsp-ui= unless =lsp-auto-configure= is set to nil.

#+begin_src emacs-lisp :tangle no
(after! lsp-ui
  :custom
  ;; (lsp-ui-doc-show 'bottom)
  ;; (lsp-ui-doc-position 'top) ;; 'at-point
  ;; (lsp-ui-doc-show-with-cursor t)
  ;; (lsp-ui-doc-enable nil) ;NOTE use K
  ;; (lsp-ui-doc-show-with-mouse t)

  ;; (lsp-ui-peek-show-directory t) ; FIXME
  (lsp-ui-peek-enable t)

  ;;;imenu
  ;; (lsp-ui-imenu-auto-refresh) ; auto refresh when necessary
  ;; (lsp-ui-imenu-refresh-delay) ;FIXME Does not exists?
  ;; (lsp-ui-imenu-buffer-position 'left)

  ;;;Sideline
  ;; (lsp-ui-sideline-enable nil)

  (lsp-ui-sideline-show-code-actions t) ;nil::
  ;; (lsp-enable-symbol-highlighting nil) ; highlight references of symbol at point eg. print in python highlight
  ;; (lsp-ui-sideline-show-hover nil) ; whether to show hover messages on sideline

  ;; (lsp-ui-sideline-enable nil)     ;t:: TODO....try this
  ;; (lsp-ui-sideline-show-diagnostics nil) ;hide only errors

  ;;; eldoc
  ;; (lsp-eldoc-enable-hover nil)

  ;;;modeline
  ;; (lsp-modeline-code-actions-enable nil)
  ;; (lsp-modeline-diagnostics-enable nil)

  ;;; lenses
  ;; (lsp-lens-enable nil)

  ;;;headerline
  (lsp-headerline-breadcrumb-enable t)

  ;;;flycheck
  ;; (lsp-diagnostics-provider :none) ; flycheck or flymake (if noflycheck is present); auto::

  ;;;completion
  ;; (lsp-completion-show-detail nil) ;t::
  ;; (lsp-completion-show-kind nil)
  ;; (lsp-completion-provider :none) ; (company mode)
  )
#+end_src

https://emacs-lsp.github.io/lsp-ui/


https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/
*** lsp treemacs
#+begin_src emacs-lisp :tangle yes
(use-package lsp-treemacs
  :after lsp-mode)                           ; TODO check if need lsp or lsp-mode
#+end_src
*** lsp-mode
#+begin_src emacs-lisp :tangle yes
(after! lsp-mode
  (setq lsp-enable-symbol-highlighting nil
        lsp-enable-suggest-server-download nil))
#+end_src
** c
*** ccls - ❄️
#+begin_src elisp :tangle yes
(after! ccls
  (setq ccls-initialization-options '(:index (:comments 2) :completion (:detailedLabel t)))
  (set-lsp-priority! 'ccls 1))
#+end_src

*** clang
lsp mode with clangd
#+begin_src elisp :tangle no
(after! lsp-clangd
  (setq lsp-clients-clangd-args
        '("-j=3"
          "--background-index"
          "--clang-tidy"
          "--completion-style=detailed"
          "--header-insertion=never"
          "--header-insertion-decorators=0"))
  (set-lsp-priority! 'clangd 2))
#+end_src

** nix
https://github.com/NixOS/nix-mode
*** nil lsp
nil: An incremental analysis assistant for writing in Nix.
#+begin_src emacs-lisp :tangle yes
(use-package! lsp-nix
  ;; :ensure lsp-mode
  :after (lsp-mode)
  :demand t
  :custom
  (lsp-disabled-clients '((nix-mode . nix-nixd))) ;; TODO test if nixdd is on or need disabling
  (lsp-nix-nil-formatter ["nixfmt"]))
#+end_src

*** nixd
#+begin_src emacs-lisp :tangle no
(use-package! nix-mode
:after lsp-mode
:ensure nil
:hook
(nix-mode . lsp-deferred) ;; So that envrc mode will work
:custom
(lsp-disabled-clients '((nix-mode . nix-nil))) ;; Disable nil so that nixd will be used as lsp-server
:config
(setq lsp-nix-nixd-server-path "nixd"
      lsp-nix-nixd-formatting-command [ "nixfmt" ]
      lsp-nix-nixd-nixpkgs-expr "import <nixpkgs> { }"
      lsp-nix-nixd-nixos-options-expr "(builtins.getFlake \"/home/nb/nixos\").nixosConfigurations.mnd.options"
      lsp-nix-nixd-home-manager-options-expr "(builtins.getFlake \"/home/nb/nixos\").homeConfigurations.\"nb@mnd\".options"))

;; (add-hook!! 'nix-mode-hook
         ;; enable autocompletion with company
         ;; (setq company-idle-delay 0.1))
#+end_src
** QML
Quickshell site

#+begin_src elisp :tangle yes
(use-package qml-ts-mode
  :after lsp-mode
  :config
  (add-to-list 'lsp-language-id-configuration '(qml-ts-mode . "qml-ts"))
  (lsp-register-client
   (make-lsp-client :new-connection (lsp-stdio-connection '("qmlls"))
                    :activation-fn (lsp-activate-on "qml-ts")
                    :server-id 'qmlls))
  (add-hook 'qml-ts-mode-hook (lambda ()
                                (setq-local electric-indent-chars '(?\n ?\( ?\) ?{ ?} ?\[ ?\] ?\; ?,))
                                (lsp-deferred))))
#+end_src

** dotnet
#+begin_src emacs-lisp :tangle no
(use-package sharper
  :demand t
  :bind
  ("C-c n" . sharper-main-transient))
#+end_src
** direnv
#+begin_src elisp :tangle no
(use-package direnv
 :config
 (direnv-mode))
#+end_src
* DOOM functionality
** fonts
change fonts on the fly [[file:~/org/roam/20250401030930-doom_emacs.org::*To change fonts on the fly][Link to my notes]]

#+begin_src emacs-lisp :tangle yes
  (setq
    doom-symbol-font (font-spec :family "Symbols Nerd Font")
    doom-font (font-spec :family "JetBrains Mono"
                         :size 15
                         :weight 'regular)
    doom-emoji-font (font-spec :family "Noto Color Emoji")
    doom-variable-pitch-font (font-spec :family "VictorMono Nerd Font" :size 15 :weight 'semibold))
#+end_src

=Useful conditionals=
(if (string-equal (system-name) "tangier") 'regular 'regular))

=Investigate=
doom-unicode-font
doom-serif-font

=Ligatures=
#FIXME Make this work for org
#+begin_src emacs-lisp :tangle no
(set-font-ligatures! '(org-mode) ">>=" ">>-")
#+end_src
** Inbuilt stuff
*** abbrev

NOTE need to toggle abbrev mode

abbrev mode is buffer-local

#+begin_src emacs-lisp :tangle no
(define-abbrev global-abbrev-table "meab" "This is my first abbrev")
#+end_src
*** buffer location in window | display-buffer-alist

#+begin_src emacs-lisp :tangle yes
(defun darth-select-window (window)
    "NOTE Docuementation expects a window arg"
    (select-window window))

(add-to-list 'display-buffer-alist
        ;; List of display functions (Emacs will use the first successful one)
        `("\\*Occur\\*"
        (display-buffer-reuse-mode-window display-buffer-below-selected)
        ;; Parameters
        (window-height . fit-window-to-buffer)
        (dedicated . t)
        (body-function . darth-select-window)))
#+end_src

=Anatomy of an entry=
( BUFFER-MATCHER
LIST-OF-DISPLAY-FUNCTIONS
&optional PARAMETERS)

=Regex or derived-mode=
((derived-mode . notmuch-hello-mode)
  List of functions
  Parameters
  )

#+begin_src emacs-lisp :tangle no
(("^ \\*org-contact\\*" display-buffer-below-selected)
 ("^\\*diff-hl" (+popup-buffer) (actions) (side . bottom) (size)
  (window-width . 40) (window-height . 0.16) (slot) (vslot)
  (window-parameters (ttl . 5) (quit . t) (select) (modeline) (autosave)))
 ("^\\*vc-change-log" (+popup-buffer) (actions) (side . bottom) (size)
  (window-width . 40) (window-height . 0.16) (slot) (vslot)
  (window-parameters (ttl . 5) (quit . t) (select . t) (modeline) (autosave)))
 ("^\\*vc-diff" (+popup-buffer) (actions) (side . bottom)
  (size quote +popup-shrink-to-fit) (window-width . 40) (window-height . 0.16)
  (slot) (vslot)
  (window-parameters (ttl . 5) (quit . t) (select) (modeline) (autosave)))
 ("^\\*Flycheck errors\\*" (+popup-buffer) (actions) (side . bottom)
  (size . 0.25) (window-width . 40) (window-height . 0.16) (slot) (vslot)
  (window-parameters (ttl . 5) (quit . t) (select . ignore) (modeline)
                     (autosave)))
 ("^\\*Flycheck error messages\\*" (+popup-buffer) (actions) (side . bottom)
  (size) (window-width . 40) (window-height . 0.16) (slot) (vslot)
  (window-parameters (ttl . 5) (quit . t) (select) (modeline) (autosave)))
 ("^\\(?:\\*magit\\|magit:\\| \\*transient\\*\\)" nil)
 ("^\\*image-dired" (+popup-buffer) (actions) (side . bottom) (size . 0.8)
  (window-width . 40) (window-height . 0.16) (slot . 20) (vslot)
  (window-parameters (ttl . 0) (quit) (select . t) (modeline) (autosave)))
 ("^\\*org-roam: " (+popup-buffer) (actions) (side . right) (size)
  (window-width . 0.33) (window-height . 0.5) (slot . 2) (vslot)
  (window-parameters (ttl) (quit) (select . ignore) (modeline) (autosave)))
 ("\\*org-roam\\*" (+popup-buffer) (actions) (side . right) (size)
  (window-width . 0.33) (window-height . 0.5) (slot . 1) (vslot)
  (window-parameters (ttl) (quit) (select . ignore) (modeline) (autosave)))
 ("^\\*Capture\\*$\\|CAPTURE-.*$" (+popup-buffer) (actions) (side . bottom)
  (size . 0.42) (window-width . 40) (window-height . 0.16) (slot) (vslot)
  (window-parameters (ttl . 5) (quit) (select . t) (modeline)
                     (autosave . ignore)))
 ("^\\*Org-Babel" (+popup-buffer) (actions) (side . bottom) (size)
  (window-width . 40) (window-height . 0.16) (slot) (vslot)
  (window-parameters (ttl . 5) (quit . t) (select . ignore) (modeline)
                     (autosave)))
 ("^\\*Org Src" (+popup-buffer) (actions) (side . bottom) (size . 0.42)
  (window-width . 40) (window-height . 0.16) (slot) (vslot)
  (window-parameters (ttl) (quit) (select . t) (modeline . t) (autosave . t)))
 ("^\\*Org Agenda" nil)
 ("^\\*Edit Formulas\\*$" (+popup-buffer) (actions) (side . bottom)
  (size . 0.25) (window-width . 40) (window-height . 0.16) (slot . -1)
  (vslot . -2)
  (window-parameters (ttl . 0) (quit . t) (select . ignore) (modeline)
                     (autosave)))
 ("^\\*Org \\(?:Select\\|Attach\\|Table Edit\\)" (+popup-buffer) (actions)
  (side . bottom) (size . 0.25) (window-width . 40) (window-height . 0.16)
  (slot . -1) (vslot . -2)
  (window-parameters (ttl . 0) (quit . t) (select . ignore) (modeline)
                     (autosave)))
 ("^ ?\\*\\(?:Agenda Com\\|Calendar\\|Org Export Dispatcher\\)" (+popup-buffer)
  (actions) (side . bottom) (size function +popup-shrink-to-fit)
  (window-width . 40) (window-height . 0.16) (slot . -1) (vslot . -1)
  (window-parameters (ttl . 0) (quit . t) (select . ignore) (modeline)
                     (autosave)))
 ("^\\*Org Links" (+popup-buffer) (actions) (side . bottom) (size . 2)
  (window-width . 40) (window-height . 0.16) (slot . -1) (vslot . -1)
  (window-parameters (ttl . 0) (quit . t) (select . ignore) (modeline)
                     (autosave)))
 ("^\\*Ibuffer\\*$" nil)
 ("^\\*Command Line" (+popup-buffer) (actions) (side . bottom) (size . 8)
  (window-width . 40) (window-height . 0.16) (slot) (vslot)
  (window-parameters (ttl . 5) (quit . t) (select . ignore) (modeline)
                     (autosave)))
 ("^\\*evil-registers" (+popup-buffer) (actions) (side . bottom) (size . 0.3)
  (window-width . 40) (window-height . 0.16) (slot) (vslot)
  (window-parameters (ttl . 5) (quit . t) (select . ignore) (modeline)
                     (autosave)))
 (#[(bufname _)
    ((if (boundp '+eval-repl-mode)
         (progn (buffer-local-value '+eval-repl-mode (get-buffer bufname)))))
    (t)]
  (+popup-buffer) (actions) (side . bottom) (size . 0.25) (window-width . 40)
  (window-height . 0.16) (slot) (vslot)
  (window-parameters
   (ttl
    . #[(buf)
        ((if (plist-get +eval-repl-plist :persist) nil
           (let* ((process (and t (get-buffer-process buf))))
             (if process
                 (progn
                   (set-process-query-on-exit-flag process nil)
                   (kill-process process) (kill-buffer buf))
               nil))))
        (t)])
   (quit) (select . ignore) (modeline) (autosave)))
 ("^\\*\\(?:Proced\\|timer-list\\|Abbrevs\\|Output\\|Occur\\|unsent mail.*?\\|message\\)\\*"
  nil)
 ("^\\*Process List\\*" (+popup-buffer) (actions) (side . bottom) (size . 0.25)
  (window-width . 40) (window-height . 0.16) (slot) (vslot . 101)
  (window-parameters (ttl . 5) (quit . t) (select . t) (modeline) (autosave)))
 ("^\\*Memory-Profiler-Report " (+popup-buffer) (actions) (side . bottom) (size)
  (window-width . 0.5) (window-height . 0.4) (slot . 2) (vslot . 100)
  (window-parameters (ttl . 5) (quit) (select . ignore) (modeline) (autosave)))
 ("^\\*CPU-Profiler-Report " (+popup-buffer) (actions) (side . bottom) (size)
  (window-width . 0.5) (window-height . 0.4) (slot . 1) (vslot . 100)
  (window-parameters (ttl . 5) (quit) (select . ignore) (modeline) (autosave)))
 ("^\\*Backtrace" (+popup-buffer) (actions) (side . bottom) (size . 0.4)
  (window-width . 40) (window-height . 0.16) (slot) (vslot . 99)
  (window-parameters (ttl . 5) (quit) (select . ignore) (modeline) (autosave)))
 ("^\\*Warnings" (+popup-buffer) (actions) (side . bottom) (size . 0.25)
  (window-width . 40) (window-height . 0.16) (slot) (vslot . 99)
  (window-parameters (ttl . 5) (quit . t) (select . ignore) (modeline)
                     (autosave)))
 ("^\\*info\\*$" (+popup-buffer) (actions) (side . bottom) (size . 0.45)
  (window-width . 40) (window-height . 0.16) (slot . 2) (vslot . 2)
  (window-parameters (ttl . 5) (quit . t) (select . t) (modeline) (autosave)))
 ("^\\*xwidget" (+popup-buffer) (actions) (side . bottom) (size . 0.35)
  (window-width . 40) (window-height . 0.16) (slot) (vslot . -11)
  (window-parameters (ttl . 5) (quit . t) (select) (modeline) (autosave)))
 ("^\\*eww\\*" (+popup-buffer) (actions) (side . bottom) (size . 0.35)
  (window-width . 40) (window-height . 0.16) (slot) (vslot . -11)
  (window-parameters (ttl . 5) (quit . t) (select . t) (modeline) (autosave)))
 ("^\\*\\([Hh]elp\\|Apropos\\)" (+popup-buffer) (actions) (side . bottom)
  (size . 0.42) (window-width . 40) (window-height . 0.16) (slot . 2)
  (vslot . -8)
  (window-parameters (ttl . 5) (quit . t) (select . t) (modeline) (autosave)))
 ("^ \\*undo-tree\\*" (+popup-buffer) (actions) (side . left) (size . 20)
  (window-width . 40) (window-height . 0.16) (slot . 2) (vslot)
  (window-parameters (ttl . 5) (quit . t) (select . t) (modeline) (autosave)))
 ("^\\*Customize" (+popup-buffer) (actions) (side . right) (size . 0.5)
  (window-width . 40) (window-height . 0.16) (slot . 2) (vslot)
  (window-parameters (ttl . 5) (quit) (select . t) (modeline) (autosave)))
 ("^\\*Calc" (+popup-buffer) (actions) (side . bottom) (size . 0.4)
  (window-width . 40) (window-height . 0.16) (slot) (vslot . -7)
  (window-parameters (ttl . 0) (quit) (select . t) (modeline) (autosave)))
 ("^\\*\\(?:Wo\\)?Man " (+popup-buffer) (actions) (side . bottom) (size . 0.45)
  (window-width . 40) (window-height . 0.16) (slot) (vslot . -6)
  (window-parameters (ttl . 0) (quit . t) (select . t) (modeline) (autosave)))
 ("^\\*doom:\\(?:v?term\\|e?shell\\)-popup" (+popup-buffer) (actions)
  (side . bottom) (size . 0.35) (window-width . 40) (window-height . 0.16)
  (slot) (vslot . -5)
  (window-parameters (ttl) (quit) (select . t) (modeline) (autosave)))
 ("^\\*doom:" (+popup-buffer) (actions) (side . bottom) (size . 0.35)
  (window-width . 40) (window-height . 0.16) (slot) (vslot . -4)
  (window-parameters (ttl . t) (quit) (select . t) (modeline . t) (autosave . t)))
 ("^\\*\\(?:doom \\|Pp E\\)" (+popup-buffer) (actions) (side . bottom)
  (size . +popup-shrink-to-fit) (window-width . 40) (window-height . 0.16)
  (slot) (vslot . -3)
  (window-parameters (ttl . 0) (quit . t) (select . ignore) (modeline)
                     (autosave . t)))
 ("^\\*\\(?:[Cc]ompil\\(?:ation\\|e-Log\\)\\|Messages\\)" (+popup-buffer)
  (actions) (side . bottom) (size . 0.3) (window-width . 40)
  (window-height . 0.16) (slot) (vslot . -2)
  (window-parameters (ttl) (quit . t) (select . ignore) (modeline)
                     (autosave . t)))
 ("^\\*Local variables\\*$" (+popup-buffer) (actions) (side . bottom)
  (size . +popup-shrink-to-fit) (window-width . 40) (window-height . 0.16)
  (slot . 1) (vslot . -1)
  (window-parameters (ttl . 5) (quit . t) (select . ignore) (modeline)
                     (autosave)))
 ("^\\*Completions" nil)
 ("^ \\*" (+popup-buffer) (actions) (side . bottom)
  (size . +popup-shrink-to-fit) (window-width . 40) (window-height . 0.16)
  (slot . 1) (vslot . -1)
  (window-parameters (ttl . 5) (quit . t) (select . ignore) (modeline)
                     (autosave)))
 ("^\\*" (+popup-buffer) (actions) (side . bottom) (size) (window-width . 40)
  (window-height . 0.16) (slot . 1) (vslot . -1)
  (window-parameters (ttl . 5) (quit . t) (select . t) (modeline) (autosave))))
#+end_src

** modeline
*** Active | Inactive
works !!...height too small thought :height 0.9

#+begin_src emacs-lisp :tangle yes
(custom-set-faces!
  ;; '(mode-line :family "Iosevka Comfy" :size 15)
  '(mode-line :family "Mononoki Nerd Font" :box nil :overline nil)
  ;; '(doom-modeline-buffer-modified :foreground "green") ; color of modified buffer indicator
  '(mode-line-inactive :family "Iosevka Comfy"))
#+end_src

#+RESULTS:
: -1

=Nice Fonts=
+ Mononoki Nerd Font
+ SpaceMono Nerd Font
+ VictorMono Nerd Font

*** battery
#+begin_src emacs-lisp :tangle no
(if (string= (system-name) "tangier") ;; battery on TANGIER
    (progn
      (setq doom-modeline-battery t)
      (display-battery-mode 1))
  (setq doom-modeline-battery nil))
#+end_src

** folder clean up | projectile
Projectile, lsp-mode, and other packages create their own files to store variables and state!

#+begin_src elisp :tangle yes
(setq projectile-known-projects-file (expand-file-name "tmp/projectile-bookmarks.eld" user-emacs-directory)
      lsp-session-file (expand-file-name "tmp/.lsp-session-v1" user-emacs-directory))

(setq backup-directory-alist '(("." . "~/.local/share/Trash/files"))) ; delete to trash instead of create backup files with .el~ suffix (alot of clutter)
;; (setq user-emacs-directory (expand-file-name "~/.cache/emacs")) ;default is in .emacs dir cache
#+end_src

#+begin_src elisp :tangle yes
;; Auto-save-mode doesn't create the path automatically!
(make-directory (expand-file-name "tmp/auto-saves/" user-emacs-directory) t)

(setq auto-save-list-file-prefix (expand-file-name "tmp/auto-saves/sessions/" user-emacs-directory)
      auto-save-file-name-transforms `((".*" ,(expand-file-name "tmp/auto-saves/" user-emacs-directory) t)))
#+end_src

https://www.gnu.org/software/emacs/manual/html_node/emacs/Auto-Save-Files.html#Auto-Save-Files

** keybindings
#+begin_src emacs-lisp :tangle no
;; (keymap-global-set "M-;" 'save-buffer) ;easier saving
;; (keymap-global-set "U" 'evil-redo) ;easier redo :)
#+end_src
** emacs sane
#+begin_src elisp :tangle yes
(use-package! emacs
  ;; :init
  ;; Put Emacs auto-generated junk in a separate file
  ;; (setq custom-file (expand-file-name "custom.el" doom-user-dir))
  :custom
  ;; (org-super-agenda-mode t)
  (tab-width 2)
  (tab-always-indent 'complete)
  (tab-first-completion 'word) ;; word 'word-or-paren-or-punct)
  ;; (completion-styles '(orderless basic partial-completion emacs22)) ; flex (orderless basic) ; flex -fuzzy find
  (display-line-numbers-type nil) ;numbers, relative , - perfomance enhance...turn on if needed
  ;; (auto-save-default t)
  ;; (auto-save-timeout 10)
  ;; (auto-save-interval 200)
  ;; (undo-limit 80000000)
  (delete-by-moving-to-trash t) ; use system trash can
  ;; (x-stretch-cursor t) ; see if needed really
  (bookmark-save-flag 1) ; TODO see docs
  ;; (uniquify-buffer-name-style 'post-forward) ;nil::
  (inhibit-startup-message t)           ;Hide th startup message

  (doom-fallback-buffer-name "Doom Emacs") ; *doom*
  (+doom-dashboard-name "Doom Dashboard")

  (+evil-want-o/O-to-continue-comments nil) ; o/O does not continue comment to next new line 😸
  ;; (evil-move-cursor-back nil)               ; don't move cursor back one CHAR when exiting insert mode

  (evil-shift-width 2)

  (user-full-name "Justin Malu") ; foor GPG config, email clients, file templates & snippets ; optional
  (user-mail-address "justinmalu@gmail.com")

  ;;; using ultra scroll block now
  (scroll-margin 18) ; Adjust the number as needed
  (scroll-conservatively 101) ; TODO test usefulness

  (doom-modeline-modal nil)             ;display mode -> NORMAL,INSERT,VISUAL
  (doom-modeline-check-simple-format t)
  ;;(display-time-mode 1)                             ; Enable time in the line-mode
  ;; (display-time-format "%H:%M")
  ;;(display-time-default-load-average nil)
  ;; (display-time-day-and-date 1)

  :config
  ;; (global-set-key [escape] 'keyboard-escape-quit) ; By default, Emacs requires you to hit ESC three times to escape quit the minibuffer. ; test this further
  (global-auto-revert-mode t)
  (drag-stuff-global-mode 1)
  (drag-stuff-define-keys)
  ;; (vi-tilde-fringe-mode -1)

  :bind
  ((
   :map evil-normal-state-map
        ;;;misc
        ("M-;" . save-buffer)
        ("<mouse-8>" . previous-buffer)
        ("<mouse-9>" . next-buffer)
        ("C-M-o" . consult-outline)

        ;;; EOL, BOL
        ("M-l" . end-of-line) ; clash with other settings - capitalise, org-metaright
        ("M-h" . beginning-of-line-text)
        ("M-S-l" . end-of-visual-line)
        ("M-S-h" . beginning-of-visual-line)

        ;;; insert newline below/above
        ("M-o" . +evil/insert-newline-below)
        ("M-O" . +evil/insert-newline-above)
    :map doom-leader-map ("to" . hl-todo-occur)
    ) ; bind conses
    ); end bind
  )
;; ("U" . evil-redo)
#+end_src

#+begin_src emacs-lisp :tangle yes
(customize-set-variable 'uniquify-buffer-name-style 'post-forward)
(customize-set-variable 'uniquify-separator " ❄ ") ;💎 🧿💢
#+end_src

** format +onsave disabled modes
#+begin_src emacs-lisp :tangle yes
(customize-set-variable '+format-on-save-disabled-modes '(nxml-mode)) ;Android studio
#+end_src
** delete spaces, tabs, newline
#+begin_src emacs-lisp :tangle yes
(setq backward-delete-char-untabify-method 'all)
#+end_src

+ all - all whitespace - tabs, spaces, \n
+ hungry - all whitespace - tabs, spaces
+ untabify - turn a tab into many spaces, then delete one space at a time

** creating a new window switches cursor to it
#+begin_src emacs-lisp :tangle yes
 (defun split-and-follow-horizontally ()
	(interactive)
	(split-window-below)
	(balance-windows)
	(other-window 1))
 (global-set-key (kbd "C-x 2") 'split-and-follow-horizontally)

 (defun split-and-follow-vertically ()
	(interactive)
	(split-window-right)
	(balance-windows)
	(other-window 1))
 (global-set-key (kbd "C-x 3") 'split-and-follow-vertically)
#+end_src
** experiment
*** initial buffer
 #+begin_src emacs-lisp :tangle no
(setq initial-buffer-choice "~/.doom.d/config.org") ;
 #+end_src

*** custom start mode

#+begin_src emacs-lisp :tangle no
(define-minor-mode start-mode
  "Provide functions for custom start page"
  :lighter " start"
  :keymap (let ((map (make-sparse-keymap)))
                (evil-define-key 'normal start-mode-map
                  (kbd "1") '(lambda () (interactive) (find-file "~/.doom.d/packages.org")))
                map))
;;(add-hook! 'start-mode-hook 'read-only-mode) ;;make start org read only
(provide 'start-mode)
#+end_src

*** witchmacs stuff

https://github.com/snackon/Witchmacs/

=Witchmacs= :witch:
#+begin_src emacs-lisp :tangle no
(setq-default tab-width 4)
(setq-default standard-indent 4)
(setq c-basic-offset tab-width)
(setq-default electric-indent-inhibit t)
(setq-default indent-tabs-mode t)
(setq backward-delete-char-untabify-method 'nil)
#+end_src

*** hide #+begin_src end_src blocks
**** FIX does not work well...with doom? better way?
see plugin options
#+begin_src emacs-lisp :tangle no
(let ((background-color (face-attribute 'default :background)))
  (set-face-attribute 'org-block-begin-line nil
                      :foreground background-color
                      :background background-color))
#+end_src
*** select and type
useful in vanilla emacs?
#+begin_src emacs-lisp :tangle no
(delete-selection-mode 1)
(setq delete-selection-mode t) ;;TODO test if this works
#+end_src
**** TODO see if works/needed
*** turn yes-or-no questions into y or no
#+begin_src emacs-lisp :tangle no
(defalias 'yes-or-no-p 'y-or-n-p)
#+end_src
*** defer load most packages for quick startup
#+begin_src emacs-lisp :tangle no
(setq use-package!-always-defer t)
#+end_src
*** delete trailing whitespace
#+begin_src emacs-lisp :tangle no
(add-hook! 'after-save-hook #'delete-trailing-whitespace)
;; or
;; (add-hook! 'after-save-hook #'whitespace-cleanup)
#+end_src
unneeded since we use ws-butler which:
+ only on modified lines
+ replaces trailing whitespace with virtual whitespace
*** default workspace behaviour fix
#+begin_src emacs-lisp :tangle no
(after! persp-mode
  (setq persp-emacsclient-init-frame-behaviour-override
   `(+workspace-current-name))
)
#+end_src
** Henrik lissner tech
#+begin_src emacs-lisp :tangle no
;; Prevents some cases of Emacs flickering.
(add-to-list 'default-frame-alist '(inhibit-double-buffering . t))
#+end_src
** dashboard
#+begin_src emacs-lisp :tangle yes
;;; :ui doom-dashboard
(setq fancy-splash-image (file-name-concat doom-user-dir "gorl.jpg"))
;; Hide the menu for as minimalistic a startup screen as possible.
(setq +doom-dashboard-functions '(doom-dashboard-widget-banner))
#+end_src
* Packages
** corfu
not sure if after! init works lul

#+begin_src elisp :tangle yes
(use-package! corfu
  :init
  (customize-set-variable 'corfu-auto nil))
#+end_src


(text-mode-ispell-word-completion nil)

Hide commands in M-x which do not apply to the current mode.  Corfu

commands are hidden, since they are not used via M-x. This setting is

useful beyond Corfu.

(read-extended-command-predicate #'command-completion-default-include-p)

=tabs-always-indent=
Enable indentation+completion using the TAB key.
`completion-at-point' is often bound to M-TAB.
(setq tab-always-indent 'complete) ; try complete if indent is off

- If t, hitting TAB always just indents the current line.
- If nil, hitting TAB indents the current line if point is at the left margin
 or in the line's indentation, otherwise it inserts a "real" TAB character.
- If complete, TAB first tries to indent the current line, and if the line
was already indented, then try to complete the thing at point.

Also see =tab-first-completion.=

Some programming language modes have their own variable to control this,
e.g., c-tab-always-indent, and do not respect this variable.
** spelling
https://www.gnu.org/software/emacs/manual/html_node/emacs/Spelling.html
*** ispell
Dictionary is set by ispell-dictionary variable. Can be changed locally with the function ispell-change-dictionary.

#+begin_src emacs-lisp :tangle no
;; (setq ispell-program-name "hunspell")
(setq ispell-dictionary "en_US")
;; Or, for local dictionary settings:
(setq ispell-local-dictionary "en_US")
#+end_src

*** TODO spell-fu
always activating in org mode...keep it as hook in [[ORG]]
#+begin_src emacs-lisp :tangle no
;; (after! spell-fu
;;   (setq spell-fu-idle-delay 0.5)  ; default is 0.25
;;   ;; (setq spell-fu-faces nil)
;;   (setq spell-fu-ignore-modes (list 'org-mode) )
;;   )

(use-package! spell-fu
  ;;:defer t
  :custom
  (spell-fu-ignore-modes (list 'org-mode))
  (spell-fu-global-ignore-buffer (lambda (buf)
                                   (buffer-local-value 'buffer-read-only buf)))
  :config
  (spell-fu-global-mode -1)

  :hook
  ;; (emacs-lisp-mode . (lambda () (spell-fu-mode)))
  (org-mode . (lambda ()
              (setq-local spell-fu-faces-exclude
                '(org-block-begin-line
                  org-block-end-line
                  org-code
                  org-date
                  org-drawer org-document-info-keyword
                  org-ellipsis
                  org-link
                  org-meta-line
                  org-properties
                  org-properties-value
                  org-special-keyword
                  org-src
                  org-tag
                  org-verbatim))
                  )))
#+end_src

=Exclude faces=
#+begin_src emacs-lisp :tangle no
(setf (alist-get 'markdown-mode +spell-excluded-faces-alist)
      '(markdown-code-face
	markdown-reference-face
	markdown-link-face
	markdown-url-face
	markdown-markup-face
	markdown-html-attr-value-face
	markdown-html-attr-name-face
	markdown-html-tag-name-face))
#+end_src
** evil-nerd-commenter | better comments
#+begin_src elisp :tangle yes
(use-package! evil-nerd-commenter
  :bind ("M-/" . evilnc-comment-or-uncomment-lines))
#+end_src

** highlight TODO
#+begin_src emacs-lisp :tangle yes
(use-package! hl-todo
  :hook (org-mode . hl-todo-mode)
  :config
  (setq hl-todo-highlight-punctuation ":"
        hl-todo-keyword-faces `(("TODO"       warning bold)
                                ("FIXME"      error bold)
                                ("!TODO"    error bold)
                                ("HACK"       font-lock-constant-face bold)
                                ("SEEKGOD"       font-lock-constant-face bold)
                                ("KESHO"       font-lock-constant-face bold)
                                ("REVIEW"     font-lock-keyword-face bold)
                                ("NOTE"       success bold)
                                ("DEPRECATED" font-lock-doc-face bold))))
#+end_src

** electric TODO test further
SCHEDULED: <2025-11-29 Sat 19:00>
#+begin_src emacs-lisp :tangle no
(setq electric-pair-pairs '(
                            (?\{ . ?\})
                            (?\( . ?\))
                            (?\[ . ?\])
                            (?\" . ?\")
                            ))
;; (electric-indent-mode -1) ; on::
  ;; (electric-pair-mode 1) ; on by default
#+end_src

** elcord
#+begin_src emacs-lisp :tangle yes
(use-package! elcord
  :commands elcord-mode
  :custom
  (elcord-display-elapsed nil)
  (elcord-idle-message "Sipo Kwenye Keyboard...👻")
  :config
  ;; (elcord-mode 1)
  (setq elcord--editor-name "Church of Emacs"
        elcord-use-major-mode-as-main-icon t))
#+end_src

** org-auto-tangle
#+begin_src emacs-lisp :tangle yes
(use-package! org-auto-tangle
  :defer t
  :hook (org-mode . org-auto-tangle-mode)
  ;; :hook (org-src-mode . org-auto-tangle-mode)
  :config
  ;; (setq org-auto-tangle-default t) ; set auto_tangle: nil for buffers not to auto tangle
  (setq org-auto-tangle-babel-safelist '("~/system.org" "~/test.org")))
#+end_src

[[github:yilkalargaw/org-auto-tangle]]

** all the icons
#+begin_src elisp :tangle no
(use-package! all-the-icons
  :if (display-graphic-p))
#+end_src

#+begin_src emacs-lisp :tangle no
(use-package! all-the-icons-dired
  :hook (dired-mode . (lambda () (all-the-icons-dired-mode t))))
#+end_src
** projectile
Does nothing... recurisive search as const eg
#+begin_src emacs-lisp :tangle no
(setq projectile-project-search-path '("~/projects/" "~/work/" ("~/github" . 1)))
#+end_src

#+begin_src elisp :tangle yes
(use-package! projectile
  :init
  (setq projectile-project-search-path '("~/.code" "~/.code/SkunkWorks/"))
  :custom
  (projectile-auto-cleanup-known-projects nil))
#+end_src
** old | phased out
*** dired
#+begin_src emacs-lisp :tangle no
(use-package! dired-open
  :config
  (setq dired-open-extensions '(("gif" . "sxiv")
                                ("jpg" . "sxiv")
                                ("png" . "sxiv")
                                ("mkv" . "mpv")
                                ("mp4" . "mpv"))))

(use-package! peep-dired
  :after dired
  :hook (evil-normalize-keymaps . peep-dired-hook)
  :config
    (evil-define-key 'normal dired-mode-map (kbd "h") 'dired-up-directory)
    (evil-define-key 'normal dired-mode-map (kbd "l") 'dired-open-file) ; use dired-find-file instead if not using dired-open package
    (evil-define-key 'normal peep-dired-mode-map (kbd "j") 'peep-dired-next-file)
    (evil-define-key 'normal peep-dired-mode-map (kbd "k") 'peep-dired-prev-file)
)
#+end_src
*** centaur tabs
#+begin_src elisp :tangle no
(use-package! centaur-tabs
  :defer t
  ;; :demand ; for when you need it immediately
  ;; :init
  ;; (setq centaur-tabs-mode nil)
  ;; (centaur-tabs-change-fonts "arial" 112)
  ;; (centaur-tabs-headline-match) ; FIXME does not work causes error
  ;; (require 'projectile)
  ;; (centaur-tabs-group-by-projectile-project) ; group tabs by projectile
  :config
  (setq centaur-tabs-set-bar nil ; left, over, under
        centaur-tabs-style 'bar ;alternate, bar, box(x), wave, zigzag, chamfer FIXME...slant does not work
        centaur-tabs-icon-type 'all-the-icons ; or nerd-icons
        centaur-tabs-set-icons t
        ;; centaur-tabs-close-button "X"
        ;; centaur-tabs-modified-marker "•" - Also
        ;; centaur-tabs-set-close-button nil
        ;; centaur-tabs-plain-icons t ; for same color as text
        ;; centaur-tabs-show-navigation-buttons t
        centaur-tabs-gray-out-icons 'buffer
        centaur-tabs-cycle-scope 'tabs ; default::, tabs , groups
        centaur-tabs-height 15)
  :hook (
         ;; (nix-mode  . centaur-tabs-mode)
         ;; (python-mode  . centaur-tabs-mode)
         ;; (prog-mode  . centaur-tabs-mode)
         (pdf-view-mode . centaur-tabs-local-mode)
         (org-mode . centaur-tabs-local-mode)) ; no centaur tabs on org documents
  :bind
  (:map evil-normal-state-map
        ("g t" . centaur-tabs-forward)
        ("g T" . centaur-tabs-backward)))
#+end_src

  there are two faces to customize the close button string: centaur-tabs-modified-marker-unselected and centaur-tabs-modified-marker-selected


=Projectile integration=
You can group your tabs by Projectile’s project. Just use the following function in your configuration:

~(centaur-tabs-group-by-projectile-project)~
This function can be called interactively to enable Projectile grouping. To go back to centaur-tabs’s user defined (or default) buffer grouping function you can interactively call:

~(centaur-tabs-group-buffer-groups)~

You can make the headline face match the centaur-tabs-default face. This makes the tabbar have an uniform appearance. In your configuration use the following function:
~(centaur-tabs-headline-match)~

see also:
+ https://github.com/ema2159/centaur-tabs?tab=readme-ov-file#buffer-groups
+ https://github.com/ema2159/centaur-tabs?tab=readme-ov-file#tab-styles

*** ultra-scroll

#+begin_src emacs-lisp :tangle no
(use-package! ultra-scroll
  :ensure nil
  ;:vc (:url "https://github.com/jdtsmith/ultra-scroll") ; if desired (emacs>=v30)
  :init
  (setq scroll-conservatively 101 ; or whatever value you prefer, since v0.4
        scroll-margin 0)        ; important: scroll-margin>0 not yet supported
  :config
  (ultra-scroll-mode 1))
#+end_src

https://github.com/jdtsmith/ultra-scroll

Do you need this?
If you don't scroll with a high-speed device (modern mouse or track-pad), no. If you do, but aren't sure, here's a good test to try:

Open a heavy emacs buffer full screen on your largest monitor.
While scrolling smoothly such that lines would move across your window's full height in about 5 seconds, can you easily read the text you see, without stopping, in both directions? Now, try this exercise again with your browser – I bet it's very readable there.
Shouldn't emacs be like this?

If you scroll buffers with tall images visible, this is also a good reason to give ultra-scroll a try.

*** emms
#+begin_src elisp :tangle no
(emms-all)
(emms-add-directory-tree "/home/malu/Music/")
(setq emms-player-list '(emms-player-mpv)
      emms-info-functions '(emms-info-native
                            ;; emms-info-metaflac ;FIXME not found
                            ;; emms-info-ogginfo
                            ))
#+end_src
*** company
#+begin_src elisp :tangle no
;; (after! company
(use-package! company
  ;; :after lsp-mode
  ;; :hook
  ;; (lsp-mode . company-mode)
  ;; (evil-normal-state-entry #'company-abort )
  ;; (after-init 'global-company-mode)
  :defer t
  :custom
  (company-idle-delay (lambda () (if (company-in-string-or-comment) nil 0.3))) ; delay in seconds 0.3;;
  ;; (company-idle-delay 0.0)
  (company-minimum-prefix-length 2)
  (company-selection-wrap-around t)
  (company-show-numbers t)
  (company-require-match 'never) ; dont need to pick a choice
  (company-tooltip-limit 6)
  :bind
  (:map company-active-map
        ;; ("<tab>" . company-complete-selection)
        ;; ("<tab>" . company-select-next-or-abort)
        ;; ("<tab>" . company-select-next)
        ;; ("backtab" . company-select-previous)
        ("RET" . company-complete-selection)
        ("<escape>" . company-abort)))
#+end_src

Company is a text and code completion framework for Emacs. The name stands for "complete anything".

It uses pluggable back-ends and front-ends to retrieve and display completion candidates.

It comes with several back-ends such as Clang, Ispell, CMake, BBDB, Yasnippet, Dabbrev, Etags, Gtags, Files, Keywords and others.
And the CAPF back-end provides a bridge to the standard completion-at-point-functions facility, and thus works with any major mode that uses the common protocol.

To see or change the list of enabled back-ends, type M-x =customize-variable= RET company-backends. Also see its description for information on writing a back-end.

Once installed, enable company-mode with M-x =company-mode=.

usage:
|-----------------------+------------------------------------------------------|
| =C-n / C-p=             | up / down                                            |
| =C-s C-r C-o=           | search through completions                           |
| =M-<digit>=             | quickly complete with one of the first 10 candidates |
| =M-x: company-complete= | to initiate completion manually                      |
|-----------------------+------------------------------------------------------|
source:[[http://company-mode.github.io/manual/Getting-Started.html#Commands-1]]

*** obsidian
#+begin_src emacs-lisp :tangle no
(setq obsidian-directory "~/OBSIDIAN")
#+end_src

#+begin_src emacs-lisp :tangle no
(use-package! obsidian
  :config
  (global-obsidian-mode t)
  (obsidian-backlinks-mode t)
  :custom
  ;; location of obsidian vault
  (obsidian-directory "~/OBSIDIAN")
  ;; Default location for new notes from `obsidian-capture'
  (obsidian-inbox-directory "Inbox")
  ;; Useful if you're going to be using wiki links
  (markdown-enable-wiki-links t)

  ;; These bindings are only suggestions; it's okay to use other bindings
  :bind (:map obsidian-mode-map
              ;; Create note
              ("C-c C-n" . obsidian-capture)
              ;; If you prefer you can use `obsidian-insert-wikilink'
              ("C-c C-l" . obsidian-insert-link)
              ;; Open file pointed to by link at point
              ("C-c C-o" . obsidian-follow-link-at-point)
              ;; Open a different note from vault
              ("C-c C-p" . obsidian-jump)
              ;; Follow a backlink for the current file
              ("C-c C-b" . obsidian-backlink-jump)))
#+end_src

*** FIXME git time machine
#+begin_src emacs-lisp :tangle no
(use-package! git-timemachine
  :after git-timemachine
  :hook (evil-normalize-keymaps . git-timemachine-hook)
  :config
    (evil-define-key 'normal git-timemachine-mode-map (kbd "C-j") 'git-timemachine-show-previous-revision)
    (evil-define-key 'normal git-timemachine-mode-map (kbd "C-k") 'git-timemachine-show-next-revision)
)
#+end_src

*** FIXME Dashboard
#+begin_src emacs-lisp :tangle no
(use-package! dashboard
  :ensure nil
  :init
  (setq initial-buffer-choice 'dashboard-open)
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-banner-logo-title "Glorious lisp interpreter")
  ;;(setq dashboard-startup-banner 'logo) ;; use standard emacs logo as banner
  (setq dashboard-startup-banner "~/Shibuya/assets/emacs/emacs-dash.png")  ;; use custom image as banner
  (setq dashboard-center-content t) ;; set to 't' for centered content
  (setq dashboard-items '((recents . 5)
                          (agenda . 5 )
                          (bookmarks . 3)
                          (projects . 3)))
  :custom
  (dashboard-modify-heading-icons '((recents . "file-text")
				      (bookmarks . "book")))
  :config
  (dashboard-setup-startup-hook))
#+end_src

*** Deft
#+begin_src elisp :tangle no
(setq deft-directory "~/org/deft"
      ;; deft-recursive t
      deft-extensions '("org" "txt"))
#+end_src
*** Async
#+begin_src emacs-lisp :tangle no
(use-package! async
  :ensure nil
  :init
  (dired-async-mode 1)) ;Do dired actions asynchronously.
#+end_src

* Terminal Modes
** ESHELL
Cannot handle ncurses programs and in certain interpreters (Python, GHCi) selecting previous commands does not work (for now).

I recommend using eshell for light cli work, and using your external terminal emulator of choice for heavier tasks
** FIXME term-mode
#+begin_src elisp :tangle no
(use-package! term
  :ensure nil
  :config
  (setq explicit-shell-file-name "bash")
  ;;(setq explicit-zsh-args '())
  (setq term-prompt-regexp "^[^#$%>\n]*[#$%>] *"))
#+end_src
* MU4E
** =My Config=
#+begin_src emacs-lisp :tangle no
(use-package! mu4e
  :custom
  (mu4e-use-fancy-chars t)
  (mu4e-attachment-dir "~/Documents/Mail/DownloadedAttachement/")
  :config
  (setq mu4e-maildir "/home/malu/Documents/Mail"
        ;; mu4e-user-mail-address-list '("foo@bar.com" "cuux@example.com"
        ;; mu4e-sent-messages-behavior 'delete
        mu4e-maildir-shortcuts '(("/INBOX" . ?i)
                                  ("/[Gmail].Sent Mail" . ?s)
                                  ("/[Gmail].Trash" . ?t)
                                  ("/[Gmail].All Mail" . ?a))
(setq message-send-mail-function 'smtpmail-send-it
    starttls-use-gnutls t
    smtpmail-starttls-credentials '(("smtp.gmail.com" 587 nil nil))
    smtpmail-auth-credentials
      '(("smtp.gmail.com" 587 "justinmalu@gmail.com" nil))
    smtpmail-default-smtp-server "smtp.gmail.com"
    smtpmail-smtp-server "smtp.gmail.com"
    smtpmail-smtp-service 587)    
  )
#+end_src

** Inspo

#+begin_src elisp :tangle no
(defvar my-mu4e-path
  (car (file-expand-wildcards "/nix/store/*-mu-*/share/emacs/site-lisp/mu4e/")))

(use-package mu4e
  ;; :load-path "/usr/share/emacs/site-lisp/mu4e/"
  ;; :load-path "/nix/store/*share/emacs/site-lisp/mu4e/"
  ;; :load-path "/nix/store/lfa1mdkbj5m06nvaxh8minq2lvxdi4z4-mu-1.12.9-mu4e/share/emacs/site-lisp/mu4e/"
  :load-path my-mu4e-path
  :defer 20 ; Wait until 20 seconds after startup
  :config
  ;; This is set to 't' to avoid mail syncing issues when using mbsync
  (setq mu4e-change-filenames-when-moving t)

  ;; Refresh mail using isync every 10 minutes
  (setq mu4e-update-interval (* 10 60))
  (setq mu4e-get-mail-command "mbsync -a")
  (setq mu4e-maildir "~/Documents/Mail")

  (setq mu4e-drafts-folder "/[Gmail]/Drafts")
  (setq mu4e-sent-folder   "/[Gmail]/Sent Mail")
  (setq mu4e-refile-folder "/[Gmail]/All Mail")
  (setq mu4e-trash-folder  "/[Gmail]/Trash")

  (setq mu4e-maildir-shortcuts
      '(("/Inbox"             . ?i)
        ("/[Gmail]/Sent Mail" . ?s)
        ("/[Gmail]/Trash"     . ?t)
        ("/[Gmail]/Drafts"    . ?d)
        ("/[Gmail]/All Mail"  . ?a))))
#+end_src

#+begin_src elisp :tangle no
  (set-email-account! "justinmalu@gmail.com"
    '((mu4e-sent-folder       . "/bar.com/Sent Mail")
      (mu4e-drafts-folder . "/[Gmail]/Drafts")
      (mu4e-sent-folder . "/[Gmail]/Sent Mail")
      (mu4e-refile-folder . "/[Gmail]/All Mail")
      (mu4e-trash-folder  . "/[Gmail]/Trash")
      ;; (smtpmail-smtp-user     . "foo@bar.com")
      (user-mail-address      . "justinmalu@gmail.com")    ;; only needed for mu < 1.4
      (mu4e-compose-signature . "---\nYours truly\nJustin Malu"))
    t)
#+end_src
* ORG
** my settings

#+begin_src emacs-lisp :tangle yes
(use-package! org
  :init
  (setq org-directory "~/org" ; trailing slash important or use expand-file-name(convert file name to absolute and canonicalize/standardize it)
        ;; org-default-notes-file (concat org-directory "/notes.org")
        org-agenda-files (list org-directory)
        org-default-notes-file (expand-file-name  "notes.org" org-directory))
  :hook
  (org-mode . (lambda ()
                ;; (vi-tilde-fringe-mode -1)
                ;; (display-line-numbers-mode -1) ;; in emacs init now so no need
                (abbrev-mode)
                (spell-fu-mode -1)
                (diff-hl-mode -1)))
  :config
  (defun my-current-time ()
    (insert (format-time-string "%A,%B %e%t%T")))
  (define-abbrev org-mode-abbrev-table "mytime" "" 'my-current-time)
  :custom
  ;; (org-fancy-priorities-list '("⚡" "⬆" "⬇" "☕"))
  (org-log-done 'time) ; task done with timestamp
  ;; (org-log-done-with-time nil)
  ;; (org-log-done 'note) ;task done with note prompted to user
  (org-log-into-drawer t)
  (org-hide-emphasis-markers t)

  (org-tag-alist
      '(;;Places
        ("@home" . ?H)
        ("@school" . ?S)
        ("@babe" . ?B)
        ;;devices
        ("@carthage" . ?C)
        ("@tangier" . ?T)
        ;;activites
        ("@work" . ?W)
        ("@pyrple" . ?P)
        ("youtubr" . ?Y)
        ("@emacs" . ?E)
        ("@nix" . ?N)))

  (org-todo-keywords
      '((sequence "TODO(t)" "WAIT(w!)"  "|" "DONE(d!)" "CANCEL(c!)"))))
  ;; (org-todo-keywords
  ;;     '((sequence "TODO(t)" "|" "DONE(d)")
  ;;       (sequence "REPORT(r)" "BUG(b)" "KNOWNCAUSE(k)" "|" "FIXED(f)")))
#+end_src

[[https://orgmode.org/orgguide.html#Properties]]

*** experiments
**** zaiste
#+begin_src emacs-lisp :tangle no
(after! org
  (set-face-attribute 'org-link nil
                      :weight 'normal
                      :background nil)
  (set-face-attribute 'org-code nil
                      :foreground "#a9a1e1"
                      :background nil)
  (set-face-attribute 'org-date nil
                      :foreground "#5B6268"
                      :background nil)
  (set-face-attribute 'org-level-1 nil
                      :foreground "steelblue2"
                      :background nil
                      :height 1.2
                      :weight 'normal)
  (set-face-attribute 'org-level-2 nil
                      :foreground "slategray2"
                      :background nil
                      :height 1.0
                      :weight 'normal)
  (set-face-attribute 'org-level-3 nil
                      :foreground "SkyBlue2"
                      :background nil
                      :height 1.0
                      :weight 'normal)
  (set-face-attribute 'org-level-4 nil
                      :foreground "DodgerBlue2"
                      :background nil
                      :height 1.0
                      :weight 'normal)
  (set-face-attribute 'org-level-5 nil
                      :weight 'normal)
  (set-face-attribute 'org-level-6 nil
                      :weight 'normal)
  (set-face-attribute 'org-document-title nil
                      :foreground "SlateGray1"
                      :background nil
                      :height 1.75
                      :weight 'bold)
#+end_src

**** FIXME Preserve Indentation On Org-Babel-Tangle
#+begin_src emacs-lisp :tangle no
(setq org-src-preserve-indentation t)
#+end_src
**** bullets mode
#+begin_src emacs-lisp :tangle no
(setq org-bullets-bullet-list '("●" "❀" "◆" "◇" "◖" "☆" "☯" " "))
(add-hook! 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src

#TODO TEST FURTHER
#FIXME not working so far
icons:     large: "◉" "○" "✸" "✿" ;; ♥ ● ◇ ✚ ✜ ☯ ◆ ♠ ♣ ♦ ☢ ❀ ◆ ◖ ▶ |  Small :: ► • ★ ▸

org-bullets-face-name

** org-roam
#+begin_src emacs-lisp :tangle yes
;; (setq org-roam-directory (file-truename "~/org/roam"))
(setq org-roam-directory (file-truename "~/org/roam")
      org-roam-db-location (file-name-concat org-roam-directory ".org-roam.db")
      org-roam-dailies-directory "journal/") ;
  ;; :custom
  ;; (org-roam-completion-everywhere t) ;default t
  ;; :bind (("C-c n l" . org-roam-buffer-toggle)
  ;;        ("C-c n f" . org-roam-node-find)
  ;;        ("C-c n i" . org-roam-node-insert)
  ;;        ("C-c n c" . org-roam-capture)
         ;; Dailies
         ;; ("C-c n j" . org-roam-dailies-capture-today))
  ;; :config
  ;; (org-roam-db-autosync-enable))
#+end_src
** org-structure-template
#+begin_src elisp :tangle no
(add-to-list 'org-structure-template-alist
             '("ss" . "src emacs-lisp")) ;FIXME deprecated approach find new way to do this
#+end_src

#+begin_src elisp :tangle no
(with-eval-after-load 'org
  (require 'org-tempo)
  (add-to-list 'org-structure-template-alist
               '("se" . "src emacs-lisp")))

#+end_src

** org-capture
Capture lets you quickly store notes with no workflow interruption
*** escape codes
|------------------+-----------------------------------------------------------|
| special =%= escape | does                                                      |
|------------------+-----------------------------------------------------------|
| =%a=               | annotation, normally the link created with org-store-link |
| =%i=               | with active region selected, insert it at point           |
| =%t=  =%T=           | timestamp, date only, or date and time                    |
| =%^t=              | prompt for timestamp                                      |
| =%u=  =%U=           | like above, but inactive timestamps                       |
| =%?=               | after completing the template, position point here        |
| =%^=               | input/prompt                                              |
|------------------+-----------------------------------------------------------|
**** time management
dont have to select manually you can:
+ relative time +3d

*** org-capture-template
**** Current Template
#+begin_src emacs-lisp :tangle yes
(use-package! org-capture
  :bind ("C-c c" . org-capture)
  :custom
  ;; (require 'prot-org)
  (org-capture-templates '(
                           ("e" "EMACs" plain
                            (file+headline "EmacsTODO.org" "TODO emacs") ;Create if does not exist otherwise ins under it
                            "+ [ ] %?")

                           ;; NixOs
                           ("n" "nixOs" plain
                            (file+headline "nixTODO.org" "TODO nixOs")
                            "+ [ ] %?"
                            :prepend t)

                           ("a" "App Ideas" plain
                            (file+headline "appsTODO.org" "TODO App Ideas")
                            "+ [ ] %?"
                            :prepend t)

                           ;; Quickshell
                           ("Q" "Quickshell + QML")
                           ("QQ" "Quickshell" plain
                            (file+headline "QuickshellTODO.org" "TODO Quickshell")
                            "+ [ ] %?")
                           ("QM" "QML" plain
                            (file+headline "QuickshellTODO.org" "TODO QML")
                            "+ [ ] %?")

                           ;; BUCKET LIST
                           ("b" "Bucket List [ movies anime books youtube]") ; group 'em up
                           ("bm" "movies" plain
                            (file+headline "bucket-list.org" "Movies")
                            "+ [ ] %?"
                            :prepend t)
                            ("ba"  "Anime List (Movies + Series)")  ;; Just a label, optional dummy
                            ("bam" "Anime Movie"  plain
                            (file+headline "bucket-list.org" "Anime")
                            "+ [ ] %?" :prepend t)
                            ;; ANIME
                            ("bas" "Anime Series" plain
                            (file+headline "bucket-list.org" "Anime")
                            "+ [ ] %?" :prepend t)
                           ("bb" "books" plain
                            (file+headline "bucket-list.org" "Books")
                            "+ [ ] %?"
                            :prepend t)
                           ;;YOUTUBE
                           ("by" "youtube" plain
                            (file+headline "bucket-list.org" "YouTube")
                            "+ [ ] %?"
                            :prepend t)

                           ;; Learning New Languages
                           ("l" "Programming Languages")
                           ("lp" "Python" plain
                            (file+headline "ProgrammingLanguagesTODO.org" "TODO PythonLearning")
                            "+ [ ] %?")
                           ("lc" "C" plain
                            (file+headline "ProgrammingLanguagesTODO.org" "TODO C")
                            "+ [ ] %?")
                           ("ln" "Nix" plain
                            (file+headline "ProgrammingLanguagesTODO.org" "TODO Nix")
                            "+ [ ] %?")

                           ;; Life's Morsels
                           ("d" "Life's Morsels")
                           ("dw" "words [w]" plain
                            (file+headline "diction.org" "Words") ;TODO see if this can support yassnippets
                            "\n\n %?"
                            :empty-lines 1
                            :prepend t)
                           ("di" "idioms [i]" plain
                            (file+headline "diction.org" "Idioms")
                            "+ %?"
                            :empty-lines 1
                            :prepend t)
                            ("dq" "quotes [q]" plain
                            (file+headline "diction.org" "Quotes")
                            ;; Template string starts here
                            "#+begin_quote\n%i%?\n#+end_quote\n"
                            :empty-lines 1
                            :prepend t)
                            ("dp" "phrases [p]" plain
                            (file+headline "diction.org" "Phrases")
                            ;; Template string starts here
                            "#+begin_quote\n%i%?\n#+end_quote\n"
                            :empty-lines 1
                            :prepend t)
                           ("v" "Video Ideas 📷")
                           ("ve" "Emacs 📃")
                           ("vei" "Emacs ideas ✔️" plain
                            (file+headline "emacsVideoIdea.org" "Random Idea")
                            " %?"
                            :prepend t
                            :empty-lines 1
                            )
                           ("vej" "emacs jolts ✏️" plain
                            (file+headline "emacsVideoIdea.org" "Random Jolt")
                            " %?"
                            :prepend t
                            :empty-lines 1)
                           )))
#+end_src
**** old template
#+begin_src elisp :tangle no
;; ("d" "Demo Template" entry
;;   (file+headline "demo.org" "Our first heading");relative to ~/org DIR
;;   "* DEMO TEXT %?")

;; ("o" "Options in prompt" entry
;;  (file+headline "demo.org" "Our second heading")
;;  "* %^{Select your option|ONE|TWO|THREE} %?")

;;; capture region and insert into template ;; attach current time
;; ("t" "Task with a date" entry
;;  (file+headline "demo.org" "Scheduled tasks")
;;  "* %^{Select your option|ONE|TWO|THREE}\n SCHEDULED: %t\n %i %?")

;; ("p" "Prompt for input: " entry
;;     (file+headline "demo.org" "Our first +heading")
;;     "* %^ %?")

;; ("a" "A random template") ; group 'em up
;;     ("at" "submenu - option [t]" entry
;;      (file+headline "demo.org" "Scheduled tasks")
;;      "* %^{Select your option|ONE|TWO|THREE}\n SCHEDULED: %t\n %i %?")
#+end_src
**** docs
source: https://orgmode.org/manual/Template-elements.html

=keys=
characters only  eg. 'a' or 'ab'
=type=
|------------+--------------------------------------------------------------------|
| entry      | text with heading                                                  |
| item       | plain list item, placed in the first plain list at target location |
| checkitem  | checkbox item                                                      |
| table-line | A new line in the first table at the target location. see more     |
| plain      | text inserted as i                                                 |
|------------+--------------------------------------------------------------------|
*** shortcurts
|----------------------+-----------------+----------------------------------------------------------------------------|
| command              | keymap          | does                                                                       |
|----------------------+-----------------+----------------------------------------------------------------------------|
| org-capture          | =M-x org-capture= | start capture process, placing you into a narrowed indirect buffer to edit |
| org-capture-finalize | =C-c C-c=         |                                                                            |
| org-capture-refile   | =C-c C-w=         | Finalize the capture process by refiling the note to a different place     |
| org-capture-kill     | =C-c C-k=         | Abort the capture process and return to the previous state.                |
|----------------------+-----------------+----------------------------------------------------------------------------|
*** org-roam-capture-template :hils:
#+begin_src emacs-lisp :tangle no
(after! org-roam
  (setq org-roam-capture-templates
        `(("n" "note" plain
           ,(format "#+title: ${title}\n%%[%s/template/note.org]" org-roam-directory)
           :target (file "note/%<%Y%m%d%H%M%S>-${slug}.org")
           :unnarrowed t)
          ("r" "thought" plain
           ,(format "#+title: ${title}\n%%[%s/template/thought.org]" org-roam-directory)
           :target (file "thought/%<%Y%m%d%H%M%S>-${slug}.org")
           :unnarrowed t)
          ("t" "topic" plain
           ,(format "#+title: ${title}\n%%[%s/template/topic.org]" org-roam-directory)
           :target (file "topic/%<%Y%m%d%H%M%S>-${slug}.org")
           :unnarrowed t)
          ("c" "contact" plain
           ,(format "#+title: ${title}\n%%[%s/template/contact.org]" org-roam-directory)
           :target (file "contact/%<%Y%m%d%H%M%S>-${slug}.org")
           :unnarrowed t)
          ("p" "project" plain
           ,(format "#+title: ${title}\n%%[%s/template/project.org]" org-roam-directory)
           :target (file "project/%<%Y%m%d>-${slug}.org")
           :unnarrowed t)
          ("i" "invoice" plain
           ,(format "#+title: %%<%%Y%%m%%d>-${title}\n%%[%s/template/invoice.org]" org-roam-directory)
           :target (file "invoice/%<%Y%m%d>-${slug}.org")
           :unnarrowed t)
          ("f" "ref" plain
           ,(format "#+title: ${title}\n%%[%s/template/ref.org]" org-roam-directory)
           :target (file "ref/%<%Y%m%d%H%M%S>-${slug}.org")
           :unnarrowed t)
          ("w" "works" plain
           ,(format "#+title: ${title}\n%%[%s/template/works.org]" org-roam-directory)
           :target (file "works/%<%Y%m%d%H%M%S>-${slug}.org")
           :unnarrowed t)
          ("s" "secret" plain "#+title: ${title}\n\n"
           :target (file "secret/%<%Y%m%d%H%M%S>-${slug}.org.gpg")
           :unnarrowed t))
        ;; Use human readable dates for dailies titles
        org-roam-dailies-capture-templates
        `(("d" "default" plain ""
           :target (file+head "%<%Y-%m-%d>.org" ,(format "%%[%s/template/journal.org]" org-roam-directory))))))
#+end_src
*** inspo
**** howardism

org capture template consists of 3 parts:
+ a key binding
+ a destination, (a file, and some section in that file, like a heading, list item etc)
+ a formatting template

source:[[https://howardism.org/Technical/Emacs/capturing-intro.html][Org capturing intro Howardism]]

**** prot tech :prot:
#+begin_src elisp :tangle no
(use-package! org-capture
  :ensure nil
  :bind ("C-c c" . org-capture)
  :config
  ;; (require 'prot-org)

  (setq org-capture-templates
        `(("u" "Unprocessed" entry
           (file+headline "tasks.org" "Unprocessed")
           ,(concat "* %^{Title}\n"
                    ":PROPERTIES:\n"
                    ":CAPTURED: %U\n"
                    ":CUSTOM_ID: h:%(format-time-string \"%Y%m%dT%H%M%S\")\n"
                    ":END:\n\n"
                    "%a\n%i%?")
           :empty-lines-after 1)
          ("w" "Wishlist" entry
           (file+olp "tasks.org" "All tasks" "Wishlist")
           ,(concat "* %^{Title} %^g\n"
                    ":PROPERTIES:\n"
                    ":CAPTURED: %U\n"
                    ":CUSTOM_ID: h:%(format-time-string \"%Y%m%dT%H%M%S\")\n"
                    ":END:\n\n"
                    "%a\n%?")
           :empty-lines-after 1)
          ("t" "Task to do" entry
           (file+headline "tasks.org" "All tasks")
           ,(concat "* TODO %^{Title} %^g\n"
                    ":PROPERTIES:\n"
                    ":CAPTURED: %U\n"
                    ":CUSTOM_ID: h:%(format-time-string \"%Y%m%dT%H%M%S\")\n"
                    ":END:\n\n"
                    "%a\n%?")
           :empty-lines-after 1)
          ("s" "Select file and heading to add to" entry
           (function prot-org-select-heading-in-file)
           ,(concat "* TODO %^{Title}%?\n"
                    ":PROPERTIES:\n"
                    ":CAPTURED: %U\n"
                    ":CUSTOM_ID: h:%(format-time-string \"%Y%m%dT%H%M%S\")\n"
                    ":END:\n\n")
           :empty-lines-after 1)

          ;; NOTE 2024-11-24: I am not using this, but am keeping it
          ;; here because the approach is good.

          ;; ("c" "Clock in and do immediately" entry
          ;;  (file+headline "tasks.org" "Clocked tasks")
          ;;  ,(concat "* TODO %^{Title}\n"
          ;;           ":PROPERTIES:\n"
          ;;           ":EFFORT: %^{Effort estimate in minutes|5|10|15|30|45|60|90|120}\n"
          ;;           ":END:\n\n"
          ;;           "%a\n")
          ;;  :prepend t
          ;;  :clock-in t
          ;;  :clock-keep t
          ;;  :immediate-finish t
          ;;  :empty-lines-after 1)
          ("p" "Private lesson or service" entry
           (file "coach.org")
           #'prot-org-capture-coach
           :prepend t
           :empty-lines 1)
          ("P" "Private service clocked" entry
           (file+headline "coach.org" "Clocked services")
           #'prot-org-capture-coach-clock
           :prepend t
           :clock-in t
           :clock-keep t
           :immediate-finish t
           :empty-lines 1)))

  ;; NOTE 2024-11-10: I realised that I was not using this enough, so
  ;; I decided to simplify my setup.  Keeping it here, in case I need
  ;; it again.

  ;; (setq org-capture-templates-contexts
  ;;       '(("e" ((in-mode . "notmuch-search-mode")
  ;;               (in-mode . "notmuch-show-mode")
  ;;               (in-mode . "notmuch-tree-mode")))))
  )
#+end_src
**** templates
***** thoughtbot guy
#+begin_src emacs-lisp :tangle no
(setq org-capture-templates
      `(("t"    ;hotkey
         "Todo list item"  ; name
         entry ;type
         ;heading type and title
         (file+headline org-default-notes-file "Tasks")
         "* TODO %?\n %i\n %a" ;template
         )))
#+end_src

***** source?? - nice stuff
# default location for capture mode?
#+begin_src emacs-lisp :tangle yes
(setq org-agenda-files
      (list "~/org")
      ;; '("~/org/agenda")
      ;; (list "inbox.org")
      )
#+end_src
then we can setup a specific capture template for inbox:

#+begin_src emacs-lisp :tangle no
(setq org-capture-templates
       `(("i" "Inbox" entry  (file "inbox.org")
        ,(concat "* TODO %?\n"
                 "/Entered on/ %U"))))
#+end_src
***** capture templates :prot:
more: manual

You can use templates for different types of capture items, and for different target locations. Say you would like to use one template to create general TODO entries, and you want to put these entries under the heading ‘Tasks’ in your file ‘~/org/gtd.org’. Also, a date tree in the file ‘journal.org’ should capture journal entries. A possible configuration would look like:

If you then press =t= from the capture menu, Org will prepare the template for you like this:

#+begin_src emacs-lisp :tangle no
(setq org-capture-templates
      '(("t" "Todo" entry (file+headline "~/org/gtd.org" "Tasks")
         "* TODO %?\n  %i\n  %a")
        ("j" "Journal" entry (file+datetree "~/org/journal.org")
         "* %?\nEntered on %U\n  %i\n  %a")))
#+end_src



[[https://www.labri.fr/perso/nrougier/GTD/index.html][very nice tutorials]]
** org-agenda

(key desc type match settings files)

Doom Emacs sets (org-agenda-start-day "-3d").

*** custom agenda / maluware-org-agenda :prot:
#+begin_src emacs-lisp :tangle yes
(load! "maluware-org-agenda") ; imports maluware-orgAgenda.el

;; (setq org-agenda-files (list "inbox.org"))

(setq org-agenda-custom-commands
      `(
        ("D" "Today's view"
         ((todo "WAIT"
                ((org-agenda-overriding-header "Tasks on hold\n")))
          (agenda ""
                  ((org-agenda-block-separator nil) ;"*"
                   (org-agenda-span 1) ;7:: how many days should it span
                   (org-deadline-warning-days 0) ; remove warnings for events not for today
                   ;; (org-agenda-day-face-function (lambda (date) 'org-agenda-date)) ; remove underline on todays date
                   ;; (org-agenda-format-date "%A %-e %B %Y") ;modify date
                   ;; (org-agenda-fontify-priorities nil)
                   (org-agenda-start-day nil)
                   (org-agenda-overriding-header "\nDaily agenda view\n")))
          ))
        ("P" "Protesilaos"
         ,maluware-custom-org-daily-agenda)
        ))
#+end_src

*** olivetti-mode
#+begin_src emacs-lisp :tangle yes
;; Function to be run when org-agenda is opened
(defun org-agenda-open-hook()
  "Hook to be run when org-agenda is opened"
  (olivetti-mode))

;; Adds hooks to org agenda mode, making follow mode active in org agenda
(add-hook 'org-agenda-mode-hook 'org-agenda-open-hook)
#+end_src

*** librephoenix

#+begin_src elisp :tangle no
;; Add icons!
(setq org-agenda-category-icon-alist
      `(("Teaching.p" ,(list (all-the-icons-faicon "graduation-cap" :height 0.8)) nil nil :ascent center)
        ("Family.s" ,(list (all-the-icons-faicon "home" :v-adjust 0.005)) nil nil :ascent center)
        ("Producer.p" ,(list (all-the-icons-faicon "youtube-play" :height 0.9)) nil nil :ascent center)
        ("Bard.p" ,(list (all-the-icons-faicon "music" :height 0.9)) nil nil :ascent center)
        ("Stories.s" ,(list (all-the-icons-faicon "book" :height 0.9)) nil nil :ascent center)
        ("Author.p" ,(list (all-the-icons-faicon "pencil" :height 0.9)) nil nil :ascent center)
        ("Gamedev.s" ,(list (all-the-icons-faicon "gamepad" :height 0.9)) nil nil :ascent center)
        ("Knowledge.p" ,(list (all-the-icons-faicon "database" :height 0.8)) nil nil :ascent center)
        ("Personal.p" ,(list (all-the-icons-material "person" :height 0.9)) nil nil :ascent center)
))
#+end_src

=org super agenda=
#+begin_src elisp :tangle no
(setq org-super-agenda-groups
       '(;; Each group has an implicit boolean OR operator between its selectors.

         ;; This is the first filter, anything found here
         ;; will be placed in this group
         ;; even if it matches following groups
         (:name " Overdue" ; Name
                :scheduled past ; Filter criteria
                :order 2 ; Order it should appear in agenda view
                :face 'error) ; Font face used for text

         ;; This is the second filter, anything not found
         ;; from the first filter, but found here,
         ;; will be placed in this group
         ;; even if it matches following groups
         (:name "Personal" ; Name
                :file-path "Personal" ; Filter criteria
                :order 3 ; Order it should appear in the agenda view
                :face 'error) ; Font faced used for text

         ;; Third filter..
         (:name "Work"  ; Name
                :file-path "Work" ; Filter criteria
                :order 3 ; Order it should appear in the agenda view
                :face 'error) ; Font face used for text

         ;; Fourth filter..
         (:name " Today "  ; Optionally specify section name
                :time-grid t ; Use the time grid
                :date today ; Filter criteria
                :scheduled today ; Another filter criteria
                :order 1 ; Order it should appear in the agenda view
                :face 'warning) ; Font face used for text
        )
)
#+end_src

+ start day defaults: "-3d".
+ today is '+0d'
+ org-agenda-span: 10::

  org-agenda-date-today

*** external variable files
For neater/shorter presentation
**** defvar maluware-org-custom-daily-agenda
#+begin_src emacs-lisp :tangle maluware-org-agenda.el
(defvar maluware-custom-org-daily-agenda
  `((tags-todo "*"
     ((org-agenda-skip-function '(org-agenda-skip-if nil '(timestamp)))
      (org-agenda-skip-function
       `(org-agenda-skip-entry-if
         'notregexp ,(format "\\[#%s\\]" (char-to-string org-priority-highest))))
      (org-agenda-block-separator nil)
      (org-agenda-overriding-header "Important tasks without a date\n")))
    (agenda "" ((org-agenda-span 1)
                (org-deadline-warning-days 0)
                (org-agenda-block-separator nil)
                (org-scheduled-past-days 0)
                ;; We don't need the `org-agenda-date-today'
                ;; highlight because that only has a practical
                ;; utility in multi-day views.
                (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
                (org-agenda-format-date "%A %-e %B %Y")
                (org-agenda-overriding-header "\nToday's agenda\n")))
    (agenda "" ((org-agenda-start-on-weekday nil)
                (org-agenda-start-day "+1d")
                (org-agenda-span 3)
                (org-deadline-warning-days 0)
                (org-agenda-block-separator nil)
                (org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                (org-agenda-overriding-header "\nNext three days\n")))
    (agenda "" ((org-agenda-time-grid nil)
                (org-agenda-start-on-weekday nil)
                ;; We don't want to replicate the previous section's
                ;; three days, so we start counting from the day after.
                (org-agenda-start-day "+4d")
                (org-agenda-span 14)
                (org-agenda-show-all-dates nil)
                (org-deadline-warning-days 0)
                (org-agenda-block-separator nil)
                (org-agenda-entry-types '(:deadline))
                (org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                (org-agenda-overriding-header "\nUpcoming deadlines (+14d)\n"))))
  "Custom agenda for use in `org-agenda-custom-commands'.")
#+end_src

***** org-agenda-custom-commands
#+begin_src emacs-lisp :tangle no
(setq org-agenda-custom-commands
      `(("A" "Daily agenda and top priority tasks"
         ((tags-todo "*"
                     ((org-agenda-skip-function '(org-agenda-skip-if nil '(timestamp)))
                      (org-agenda-skip-function
                       `(org-agenda-skip-entry-if
                         'notregexp ,(format "\\[#%s\\]" (char-to-string org-priority-highest))))
                      (org-agenda-block-separator nil)
                      (org-agenda-overriding-header "Important tasks without a date\n")))
          (agenda "" ((org-agenda-span 1)
                      (org-deadline-warning-days 0)
                      (org-agenda-block-separator nil)
                      (org-scheduled-past-days 0)
                      ;; We don't need the `org-agenda-date-today'
                      ;; highlight because that only has a practical
                      ;; utility in multi-day views.
                      (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
                      (org-agenda-format-date "%A %-e %B %Y")
                      (org-agenda-overriding-header "\nToday's agenda\n")))
          (agenda "" ((org-agenda-start-on-weekday nil)
                      (org-agenda-start-day "+1d")
                      (org-agenda-span 3)
                      (org-deadline-warning-days 0)
                      (org-agenda-block-separator nil)
                      (org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                      (org-agenda-overriding-header "\nNext three days\n")))
          (agenda "" ((org-agenda-time-grid nil)
                      (org-agenda-start-on-weekday nil)
                      ;; We don't want to replicate the previous section's
                      ;; three days, so we start counting from the day after.
                      (org-agenda-start-day "+4d")
                      (org-agenda-span 14)
                      (org-agenda-show-all-dates nil)
                      (org-deadline-warning-days 0)
                      (org-agenda-block-separator nil)
                      (org-agenda-entry-types '(:deadline))
                      (org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                      (org-agenda-overriding-header "\nUpcoming deadlines (+14d)\n")))))
        ("P" "Plain text daily agenda and top priorities"
         ((tags-todo "*"
                     ((org-agenda-skip-function '(org-agenda-skip-if nil '(timestamp)))
                      (org-agenda-skip-function
                       `(org-agenda-skip-entry-if
                         'notregexp ,(format "\\[#%s\\]" (char-to-string org-priority-highest))))
                      (org-agenda-block-separator nil)
                      (org-agenda-overriding-header "Important tasks without a date\n")))
          (agenda "" ((org-agenda-span 1)
                      (org-deadline-warning-days 0)
                      (org-agenda-block-separator nil)
                      (org-scheduled-past-days 0)
                      ;; We don't need the `org-agenda-date-today'
                      ;; highlight because that only has a practical
                      ;; utility in multi-day views.
                      (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
                      (org-agenda-format-date "%A %-e %B %Y")
                      (org-agenda-overriding-header "\nToday's agenda\n")))
          (agenda "" ((org-agenda-start-on-weekday nil)
                      (org-agenda-start-day "+1d")
                      (org-agenda-span 3)
                      (org-deadline-warning-days 0)
                      (org-agenda-block-separator nil)
                      (org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                      (org-agenda-overriding-header "\nNext three days\n")))
          (agenda "" ((org-agenda-time-grid nil)
                      (org-agenda-start-on-weekday nil)
                      ;; We don't want to replicate the previous section's
                      ;; three days, so we start counting from the day after.
                      (org-agenda-start-day "+4d")
                      (org-agenda-span 14)
                      (org-agenda-show-all-dates nil)
                      (org-deadline-warning-days 0)
                      (org-agenda-block-separator nil)
                      (org-agenda-entry-types '(:deadline))
                      (org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                      (org-agenda-overriding-header "\nUpcoming deadlines (+14d)\n"))))
         ((org-agenda-with-colors nil)
          (org-agenda-prefix-format "%t %s")
          (org-agenda-current-time-string ,(car (last org-agenda-time-grid)))
          (org-agenda-fontify-priorities nil)
          (org-agenda-remove-tags t))
         ("agenda.txt"))))
#+end_src

***** org-agenda-custom-commands
#+begin_src emacs-lisp :tangle no
(setq org-agenda-custom-commands
      `(("A" "Daily agenda and top priority tasks"
         ,prot-org-custom-daily-agenda)
        ("P" "Plain text daily agenda and top priorities"
         ,prot-org-custom-daily-agenda
         ((org-agenda-with-colors nil)
          (org-agenda-prefix-format "%t %s")
          (org-agenda-current-time-string ,(car (last org-agenda-time-grid)))
          (org-agenda-fontify-priorities nil)
          (org-agenda-remove-tags t))
         ("agenda.txt"))))
#+end_src
**** experiment custom-org-daily-agenda
#+begin_src emacs-lisp :tangle no
(defvar maluware-custom-org-daily-agenda
         `((tags-todo "*"
            (org-agenda-skip-function '(org-agenda-skip-if nil '(timestamp))))
           (org-agenda-skip-function
            `(org-agenda-skip-entry-if
              'notrege))
           (todo "WAIT"
                ((org-agenda-overriding-header "Tasks on hold\n")))
         (agenda ""
                 ((org-agenda-block-separator nil) ;"*"
                  ;; (org-agenda-span 1) ;7:: how many days should it span
                  ;; (org-deadline-warning-days 0) ;events not for today
                  (org-agenda-day-face-function (lambda (date) 'org-agenda-date)) ; remove underline on todays date
                  ;; (org-agenda-format-date "%A %-e %B %Y") ;modify date
                  ;; (org-agenda-fontify-priorities nil)
                  ;; org-agenda-skip-function
                  (org-agenda-overriding-header "\nDaily agenda\n"))))
  )
#+end_src
*** from manual
#+begin_src emacs-lisp :tangle no
(setq org-agenda-custom-commands
    '(("h" "Agenda and Home-related tasks"
        ((agenda "")
        (tags-todo "home")
        (tags "garden")))
      ("o" "Agenda and Office-related tasks"
        ((agenda "")
        (tags-todo "work")
        (tags "office")))
      ))
#+end_src
*** worg tricks
**** Colorize clocking tasks with a block

[[https://orgmode.org/worg/org-hacks.html][org hacks -worg]]

#+begin_src emacs-lisp :tangle no
;; work with org-agenda dispatcher [c] "Today Clocked Tasks" to view today's clocked tasks.
(defun org-agenda-log-mode-colorize-block ()
  "Set different line spacing based on clock time duration."
  (save-excursion
    (let* ((colors (cl-case (alist-get 'background-mode (frame-parameters))
                                 ('light
                                  (list "#F6B1C3" "#FFFF9D" "#BEEB9F" "#ADD5F7"))
                                 ('dark
                                  (list "#aa557f" "DarkGreen" "DarkSlateGray" "DarkSlateBlue"))))
           pos
           duration)
      (nconc colors colors)
      (goto-char (point-min))
      (while (setq pos (next-single-property-change (point) 'duration))
        (goto-char pos)
        (when (and (not (equal pos (point-at-eol)))
                   (setq duration (org-get-at-bol 'duration)))
          ;; larger duration bar height
          (let ((line-height (if (< duration 15) 1.0 (+ 0.5 (/ duration 30))))
                (ov (make-overlay (point-at-bol) (1+ (point-at-eol)))))
            (overlay-put ov 'face `(:background ,(car colors) :foreground "black"))
            (setq colors (cdr colors))
            (overlay-put ov 'line-height line-height)
            (overlay-put ov 'line-spacing (1- line-height))))))))

(add-hook! 'org-agenda-finalize-hook #'org-agenda-log-mode-colorize-block)
#+end_src

**** Go back to the previous top-level heading
***** TODO test further
#+begin_src emacs-lisp :tangle no
(defun org-back-to-top-level-heading ()
  "Go back to the current top level heading."
  (interactive)
  (or (re-search-backward "^\* " nil t)
      (goto-char (point-min))))
#+end_src
** org-babel
#+begin_src emacs-lisp :tangle yes
(after! org
(org-babel-do-load-languages
 'org-babel-load-languages
 '((emacs-lisp . t)
   (jupyter . t))))
#+end_src
* Magit
#+begin_src emacs-lisp :tangle yes
(setq magit-view-git-manual-method 'woman)
#+end_src

* Inspo / Docs
** DOCS
*** docs | old
**** fonts
source: [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Fonts.html][emacs - fonts GNU manual]]
‘slant’
One of ‘italic’, ‘oblique’, or ‘roman’.

‘weight’
One of ‘light’, ‘medium’, ‘demibold’, ‘bold’ or ‘black’.

‘style’
Some fonts define special styles which are a combination of slant and weight. For instance, ‘Dejavu Sans’ defines the ‘book’ style, which overrides the slant and weight properties.

‘width’
One of ‘condensed’, ‘normal’, or ‘expanded’.

‘spacing’
One of ‘monospace’, ‘proportional’, ‘dual-width’, or ‘charcell’.

 Doom exposes five (optional) variables for controlling fonts in Doom:

 - `doom-font' -- the primary font to use
 - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
   - used in websites? eww?
   - headers?

**** theme
***** load theme

 There are =two ways= to load a theme. Both assume the theme is installed and
 available.

 You can either set =doom-theme= or =manually= load a theme with the =load-theme= function (This is the =default=:)

***** favs
****** dark
+ moonlight
+ ayu-mirage
+ dracula (python) -> cool purple
+ gruvbox
+ tokyonight
+ doom miramare
+ horizon - nice red accents and purple
+ bluloco-dark
+ oksolar-dark
+ solarized-dark
+ one
+ solarized-dark-high-contrast
+ material - nice purple dotts and cursor
+ snazzy

=Python=
+ monokai-octagon (python)

****** light
- doom-solarized-light
- earl grey
****** really light white light
- doom-winter-is-coming-light
- ayu light
- one light
****** pastel
+ ephemeral
+ nord-aurora
**** nerd font experiement
***** mononoki
kinda nice and kawaii
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "Mononoki Nerd Font" :size 17 :weight 'semi-bold ))
#+end_src
***** iosevka
****** comfy
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "Iosevka Comfy" :size 16 :weight 'regular ))
#+end_src
****** term
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "Iosevka Nerd Font" :size 16 :weight 'medium ))
#+end_src

***** zed mono
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "ZedMono Nerd Font" :size 17 :weight 'regular ))
#+end_src

***** martian mono
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "MartianMono Nerd Font" :size 14 :weight 'regular ))
#+end_src

***** caskaydia
****** code
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "Cascadia Code" :size 15 :weight 'semibold ))
#+end_src
****** mono
kinda nice
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "Cascadia Mono" :size 15 :weight 'semibold ))
#+end_src

***** lilex
nice l and i
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "Lilex Nerd Font" :size 15 :weight 'normal ))
#+end_src

***** fira
nice defaults
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "FiraMono Nerd Font" :size 15 :weight 'medium ))
#+end_src

***** shure
boxy nice stuff 😃
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "ShureTechMono Nerd Font" :size 15 :weight 'medium ))
#+end_src

***** lekton
nice little font actually :)
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "Lekton Nerd Font Mono" :size 18 :weight 'bold ))
#+end_src

***** space mono
use with rofi as well...clean cut font but kinda thin and no semibold
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "SpaceMono Nerd Font Mono" :size 16 :weight 'regular ))
#+end_src

***** Monofur
kawaii - but does not look nice for ide maybe for ui?
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "Monofur Nerd Font" :size 18  :weight 'regular ))
#+end_src

***** SauceCode Pro
#+begin_src emacs-lisp :tangle no
(setq
 doom-font (font-spec :family "SauceCodePro Nerd Font" :size 16  :weight 'regular ))
#+end_src

***** Geist
sublime... kinda similar to monaspace... weird ls , i is clean 0 o O
#+begin_src emacs-lisp :tangle no
(setq doom-font (font-spec :family "GeistMono Nerd Font" :size 16  :weight 'normal ))
#+end_src

***** monaspace
one family, 5 fonts, 3 variable axes


|------+---------+--------------------|
| abbr | name    | font (actual)      |
|------+---------+--------------------|
| Ne   | Neon    | Neo-grotesque sans |
| Ar   | Argon   | Humanist sans      |
| Xe   | Xenon   | Slab serif         |
| Ra   | Radon   | Handwriting        |
| Kr   | Kyrpton | Mechanical sans    |
|------+---------+--------------------|

#+begin_src emacs-lisp :tangle no
;; (setq doom-font (font-spec :family "Monaspace Neon" :size 16 :weight 'semibold ))
(setq doom-font (font-spec :family "Monaspace Krypton" :size 16 :weight 'normal ))
#+end_src

**** options
- var:doom-font: the primary font for Emacs to use.
- var:doom-variable-pitch-font: used for non-monospace fonts (e.g. when using variable-pitch-mode or mixed-pitch-mode). Popular for text modes, like Org or Markdown.
- var:doom-emoji-font: used for rendering emoji. Only needed if you want to use a font other than your operating system’s default.
- var:doom-symbol-font: used for rendering symbols.
- var:doom-serif-font: the sans-serif font to use wherever the face:fixed-pitch-serif face is used.
- var:doom-big-font: the large font to use when fn:doom-big-font-mode is active.
*** Revert Buffer

  Reverting a Buffer:
  The fundamental action is "reverting a buffer," which means replacing the current buffer's text with the text from the file on disk. This is useful when:
    + You've made changes in Emacs but want to discard them and return to the saved version.
    + Another program has modified the file, and you want to update the Emacs buffer to reflect those changes.

  Auto Revert Mode:
  Emacs also provides "auto-revert-mode," which automates this process. When enabled, Emacs periodically checks if the file on disk has changed and automatically updates the buffer. This is particularly useful for:
    + Viewing log files that are constantly being updated.
    + Keeping your Emacs buffer synchronized with files modified by other applications.
*** KeyBinds
**** Keybindings in lcoal keymaps
Only bound after the pkg is loaded
:map <mode> ( "" . <function> )
#+begin_src elisp :tangle no
(use-package helm
  :bind (:map helm-command-map
         ("C-c h" . helm-execute-persistent-action)))
#+end_src
** Justin-VC tech :justin:
*** dashboard / misc
#+begin_src emacs-lisp :tangle no
(defun +doom-dashboard-setup-modified-keymap ()
  (setq +doom-dashboard-mode-map (make-sparse-keymap))
  (map! :map +doom-dashboard-mode-map
        :desc "Find file" :ne "f" #'find-file
        :desc "Recent files" :ne "r" #'consult-recent-file
        :desc "Config dir" :ne "C" #'doom/open-private-config
        :desc "Open config.org" :ne "c" (cmd! (find-file (expand-file-name "config.org" doom-private-dir)))
        :desc "Notes (roam)" :ne "n" #'org-roam-node-find
        :desc "Search (roam)" :ne "N" #'justin/org-roam-rg-search
        :desc "Switch buffer" :ne "b" #'+vertico/switch-workspace-buffer
        :desc "Switch buffers (all)" :ne "B" #'consult-buffer
        :desc "IBuffer" :ne "i" #'ibuffer
        :desc "Agenda"  :ne "o" #'org-agenda
        :desc "Previous buffer" :ne "p" #'previous-buffer
        :desc "Set theme" :ne "t" #'consult-theme
        :desc "Quit" :ne "Q" #'save-buffers-kill-terminal
        :desc "Show keybindings" :ne "h" (cmd! (which-key-show-keymap '+doom-dashboard-mode-map))))

(add-transient-hook! #'+doom-dashboard-mode (+doom-dashboard-setup-modified-keymap))
(add-transient-hook! #'+doom-dashboard-mode :append (+doom-dashboard-setup-modified-keymap))
(add-hook! 'doom-init-ui-hook :append (+doom-dashboard-setup-modified-keymap))
#+end_src

#+begin_src emacs-lisp :tangle yes
(map! :leader :desc "Dashboard" "d" #'+doom-dashboard/open)
#+end_src

#+begin_src emacs-lisp :tangle no
(map! :n [mouse-8] #'better-jumper-jump-backward
      :n [mouse-9] #'better-jumper-jump-forward)
#+end_src

*** splash images
#+begin_src emacs-lisp :tangle no
(use-package random-splash-image
  :config
  (setq random-splash-image-dir (concat (getenv "HOME") "/.doom.d/misc/splash-images"))
  (unless (file-directory-p random-splash-image-dir)
  (make-directory random-splash-image-dir t))
  (random-splash-image-set))
#+end_src
*** eval better arrows
#+begin_src emacs-lisp :tangle yes
(setq eros-eval-result-prefix "⟹ ") ; default =>
#+end_src
*** GPT things
#+begin_src emacs-lisp :tangle no
(use-package! gptel
  :config
  (setq gptel-model "llama3:latest"
        gptel-org-branching-context t)

  (setq gptel-backend
        (gptel-make-ollama "Ollama"
                           :host "192.168.1.9:11434"
                           :stream t
                           :models '("llama3:latest"))))

(use-package! gptel-quick
  :after gptel
  :config
  ;; Add any gptel-quick specific configuration here
  )

;; Key bindings
(map! :leader
      (:prefix ("l" . "LLM")
       :desc "Quick GPTel" "q" #'gptel-quick
       :desc "Start GPTel" "s" #'gptel
       :desc "Send to GPTel" "S" #'gptel-send))
#+end_src
*** Emojify
#+begin_src emacs-lisp :tangle no
(customize-set-variable 'emojify-emoji-set "twemoji-v2")
#+end_src

+ "emojione-v2.2.6-22"
*** maginalia changes
#+begin_src emacs-lisp :tangle no
(after! marginalia
  (setq marginalia-censor-variables nil)

  (defadvice! +marginalia--anotate-local-file-colorful (cand)
    "Just a more colourful version of `marginalia--anotate-local-file'."
    :override #'marginalia--annotate-local-file
    (when-let (attrs (file-attributes (substitute-in-file-name
                                       (marginalia--full-candidate cand))
                                      'integer))
      (marginalia--fields
       ((marginalia--file-owner attrs)
        :width 12 :face 'marginalia-file-owner)
       ((marginalia--file-modes attrs))
       ((+marginalia-file-size-colorful (file-attribute-size attrs))
        :width 7)
       ((+marginalia--time-colorful (file-attribute-modification-time attrs))
        :width 12))))

  (defun +marginalia--time-colorful (time)
    (let* ((seconds (float-time (time-subtract (current-time) time)))
           (color (doom-blend
                   (face-attribute 'marginalia-date :foreground nil t)
                   (face-attribute 'marginalia-documentation :foreground nil t)
                   (/ 1.0 (log (+ 3 (/ (+ 1 seconds) 345600.0)))))))
      ;; 1 - log(3 + 1/(days + 1)) % grey
      (propertize (marginalia--time time) 'face (list :foreground color))))

  (defun +marginalia-file-size-colorful (size)
    (let* ((size-index (/ (log10 (+ 1 size)) 7.0))
           (color (if (< size-index 10000000) ; 10m
                      (doom-blend 'orange 'green size-index)
                    (doom-blend 'red 'orange (- size-index 1)))))
      (propertize (file-size-human-readable size) 'face (list :foreground color)))))
#+end_src
*** weather
#+begin_src emacs-lisp :tangle no
(use-package! wttrin
  :commands wttrin
  :config
  wttrin-default-cities '("Nairobi" ))
#+end_src
*** FIXME org-modern
#+begin_src emacs-lisp :tangle no
(use-package! org-modern
  :hook (org-mode . org-modern-mode)
  :config
  (setq org-modern-star ["◉" "○" "✸" "✿" "✤" "✜" "◆" "▶"]
        org-modern-table-vertical 1
        org-modern-table-horizontal 0.2
        org-modern-list '((43 . "➤")
                          (45 . "–")
                          (42 . "•"))
        org-modern-todo-faces
        '(("TODO" :inverse-video t :inherit org-todo)
          ("PROJ" :inverse-video t :inherit +org-todo-project)
          ("STRT" :inverse-video t :inherit +org-todo-active)
          ("[-]"  :inverse-video t :inherit +org-todo-active)
          ("HOLD" :inverse-video t :inherit +org-todo-onhold)
          ("WAIT" :inverse-video t :inherit +org-todo-onhold)
          ("[?]"  :inverse-video t :inherit +org-todo-onhold)
          ("KILL" :inverse-video t :inherit +org-todo-cancel)
          ("NO"   :inverse-video t :inherit +org-todo-cancel))
        org-modern-footnote
        (cons nil (cadr org-script-display))
  )
  (custom-set-faces! '(org-modern-statistics :inherit org-checkbox-statistics-todo)))

(setq org-modern-priority t)

(after! spell-fu
  (cl-pushnew 'org-modern-tag (alist-get 'org-mode +spell-excluded-faces-alist)))
#+end_src
